//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:05:14 PM AST 
//


package net.opengis.wfs.v_1_1_0;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * 
 *             The DescribeFeatureType operation allows a client application
 *             to request that a Web Feature Service describe one or more
 *             feature types.   A Web Feature Service must be able to generate
 *             feature descriptions as valid GML3 application schemas.
 * 
 *             The schemas generated by the DescribeFeatureType operation can
 *             be used by a client application to validate the output.
 * 
 *             Feature instances within the WFS interface must be specified
 *             using GML3.  The schema of feature instances specified within
 *             the WFS interface must validate against the feature schemas 
 *             generated by the DescribeFeatureType request.
 *          
 * 
 * <p>Java class for DescribeFeatureTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DescribeFeatureTypeType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/wfs}BaseRequestType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}QName" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="outputFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="text/xml; subtype=gml/3.1.1" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DescribeFeatureTypeType", propOrder = {
    "typeName"
})
public class DescribeFeatureTypeType
    extends BaseRequestType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElement(name = "TypeName")
    protected List<QName> typeName;
    @XmlAttribute(name = "outputFormat")
    protected String outputFormat;

    /**
     * Gets the value of the typeName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the typeName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTypeName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link QName }
     * 
     * 
     */
    public List<QName> getTypeName() {
        if (typeName == null) {
            typeName = new ArrayList<QName>();
        }
        return this.typeName;
    }

    public boolean isSetTypeName() {
        return ((this.typeName!= null)&&(!this.typeName.isEmpty()));
    }

    public void unsetTypeName() {
        this.typeName = null;
    }

    /**
     * Gets the value of the outputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputFormat() {
        if (outputFormat == null) {
            return "text/xml; subtype=gml/3.1.1";
        } else {
            return outputFormat;
        }
    }

    /**
     * Sets the value of the outputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputFormat(String value) {
        this.outputFormat = value;
    }

    public boolean isSetOutputFormat() {
        return (this.outputFormat!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<QName> theTypeName;
            theTypeName = (this.isSetTypeName()?this.getTypeName():null);
            strategy.appendField(locator, this, "typeName", buffer, theTypeName, this.isSetTypeName());
        }
        {
            String theOutputFormat;
            theOutputFormat = this.getOutputFormat();
            strategy.appendField(locator, this, "outputFormat", buffer, theOutputFormat, this.isSetOutputFormat());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final DescribeFeatureTypeType that = ((DescribeFeatureTypeType) object);
        {
            List<QName> lhsTypeName;
            lhsTypeName = (this.isSetTypeName()?this.getTypeName():null);
            List<QName> rhsTypeName;
            rhsTypeName = (that.isSetTypeName()?that.getTypeName():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "typeName", lhsTypeName), LocatorUtils.property(thatLocator, "typeName", rhsTypeName), lhsTypeName, rhsTypeName, this.isSetTypeName(), that.isSetTypeName())) {
                return false;
            }
        }
        {
            String lhsOutputFormat;
            lhsOutputFormat = this.getOutputFormat();
            String rhsOutputFormat;
            rhsOutputFormat = that.getOutputFormat();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "outputFormat", lhsOutputFormat), LocatorUtils.property(thatLocator, "outputFormat", rhsOutputFormat), lhsOutputFormat, rhsOutputFormat, this.isSetOutputFormat(), that.isSetOutputFormat())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<QName> theTypeName;
            theTypeName = (this.isSetTypeName()?this.getTypeName():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "typeName", theTypeName), currentHashCode, theTypeName, this.isSetTypeName());
        }
        {
            String theOutputFormat;
            theOutputFormat = this.getOutputFormat();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "outputFormat", theOutputFormat), currentHashCode, theOutputFormat, this.isSetOutputFormat());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof DescribeFeatureTypeType) {
            final DescribeFeatureTypeType copy = ((DescribeFeatureTypeType) draftCopy);
            {
                Boolean typeNameShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetTypeName());
                if (typeNameShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<QName> sourceTypeName;
                    sourceTypeName = (this.isSetTypeName()?this.getTypeName():null);
                    @SuppressWarnings("unchecked")
                    List<QName> copyTypeName = ((List<QName> ) strategy.copy(LocatorUtils.property(locator, "typeName", sourceTypeName), sourceTypeName, this.isSetTypeName()));
                    copy.unsetTypeName();
                    if (copyTypeName!= null) {
                        List<QName> uniqueTypeNamel = copy.getTypeName();
                        uniqueTypeNamel.addAll(copyTypeName);
                    }
                } else {
                    if (typeNameShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetTypeName();
                    }
                }
            }
            {
                Boolean outputFormatShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetOutputFormat());
                if (outputFormatShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceOutputFormat;
                    sourceOutputFormat = this.getOutputFormat();
                    String copyOutputFormat = ((String) strategy.copy(LocatorUtils.property(locator, "outputFormat", sourceOutputFormat), sourceOutputFormat, this.isSetOutputFormat()));
                    copy.setOutputFormat(copyOutputFormat);
                } else {
                    if (outputFormatShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.outputFormat = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new DescribeFeatureTypeType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof DescribeFeatureTypeType) {
            final DescribeFeatureTypeType target = this;
            final DescribeFeatureTypeType leftObject = ((DescribeFeatureTypeType) left);
            final DescribeFeatureTypeType rightObject = ((DescribeFeatureTypeType) right);
            {
                Boolean typeNameShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetTypeName(), rightObject.isSetTypeName());
                if (typeNameShouldBeMergedAndSet == Boolean.TRUE) {
                    List<QName> lhsTypeName;
                    lhsTypeName = (leftObject.isSetTypeName()?leftObject.getTypeName():null);
                    List<QName> rhsTypeName;
                    rhsTypeName = (rightObject.isSetTypeName()?rightObject.getTypeName():null);
                    List<QName> mergedTypeName = ((List<QName> ) strategy.merge(LocatorUtils.property(leftLocator, "typeName", lhsTypeName), LocatorUtils.property(rightLocator, "typeName", rhsTypeName), lhsTypeName, rhsTypeName, leftObject.isSetTypeName(), rightObject.isSetTypeName()));
                    target.unsetTypeName();
                    if (mergedTypeName!= null) {
                        List<QName> uniqueTypeNamel = target.getTypeName();
                        uniqueTypeNamel.addAll(mergedTypeName);
                    }
                } else {
                    if (typeNameShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetTypeName();
                    }
                }
            }
            {
                Boolean outputFormatShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetOutputFormat(), rightObject.isSetOutputFormat());
                if (outputFormatShouldBeMergedAndSet == Boolean.TRUE) {
                    String lhsOutputFormat;
                    lhsOutputFormat = leftObject.getOutputFormat();
                    String rhsOutputFormat;
                    rhsOutputFormat = rightObject.getOutputFormat();
                    String mergedOutputFormat = ((String) strategy.merge(LocatorUtils.property(leftLocator, "outputFormat", lhsOutputFormat), LocatorUtils.property(rightLocator, "outputFormat", rhsOutputFormat), lhsOutputFormat, rhsOutputFormat, leftObject.isSetOutputFormat(), rightObject.isSetOutputFormat()));
                    target.setOutputFormat(mergedOutputFormat);
                } else {
                    if (outputFormatShouldBeMergedAndSet == Boolean.FALSE) {
                        target.outputFormat = null;
                    }
                }
            }
        }
    }

    public void setTypeName(List<QName> value) {
        this.typeName = null;
        if (value!= null) {
            List<QName> draftl = this.getTypeName();
            draftl.addAll(value);
        }
    }

    public DescribeFeatureTypeType withTypeName(QName... values) {
        if (values!= null) {
            for (QName value: values) {
                getTypeName().add(value);
            }
        }
        return this;
    }

    public DescribeFeatureTypeType withTypeName(Collection<QName> values) {
        if (values!= null) {
            getTypeName().addAll(values);
        }
        return this;
    }

    public DescribeFeatureTypeType withOutputFormat(String value) {
        setOutputFormat(value);
        return this;
    }

    public DescribeFeatureTypeType withTypeName(List<QName> value) {
        setTypeName(value);
        return this;
    }

    @Override
    public DescribeFeatureTypeType withService(String value) {
        setService(value);
        return this;
    }

    @Override
    public DescribeFeatureTypeType withVersion(String value) {
        setVersion(value);
        return this;
    }

    @Override
    public DescribeFeatureTypeType withHandle(String value) {
        setHandle(value);
        return this;
    }

}
