//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:05:14 PM AST 
//


package net.opengis.wfs.v_1_1_0;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;
import eu.essi_lab.jaxb.filter._1_1_0.FilterType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for UpdateElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UpdateElementType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/wfs}Property" maxOccurs="unbounded"/&gt;
 *         &lt;element ref="{http://www.opengis.net/ogc}Filter" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="handle" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="typeName" use="required" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
 *       &lt;attribute name="inputFormat" type="{http://www.w3.org/2001/XMLSchema}string" default="x-application/gml:3" /&gt;
 *       &lt;attribute name="srsName" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UpdateElementType", propOrder = {
    "property",
    "filter"
})
public class UpdateElementType implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElement(name = "Property", required = true)
    protected List<PropertyType> property;
    @XmlElement(name = "Filter", namespace = "http://www.opengis.net/ogc")
    protected FilterType filter;
    @XmlAttribute(name = "handle")
    protected String handle;
    @XmlAttribute(name = "typeName", required = true)
    protected QName typeName;
    @XmlAttribute(name = "inputFormat")
    protected String inputFormat;
    @XmlAttribute(name = "srsName")
    @XmlSchemaType(name = "anyURI")
    protected String srsName;

    /**
     * 
     *                   Changing or updating a feature instance means that
     *                   the current value of one or more properties of
     *                   the feature are replaced with new values.  The Update
     *                   element contains  one or more Property elements.  A
     *                   Property element contains the name or a feature property
     *                   who's value is to be changed and the replacement value
     *                   for that property.
     *                Gets the value of the property property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the property property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProperty().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PropertyType }
     * 
     * 
     */
    public List<PropertyType> getProperty() {
        if (property == null) {
            property = new ArrayList<PropertyType>();
        }
        return this.property;
    }

    public boolean isSetProperty() {
        return ((this.property!= null)&&(!this.property.isEmpty()));
    }

    public void unsetProperty() {
        this.property = null;
    }

    /**
     * 
     *                   The Filter element is used to constrain the scope
     *                   of the update operation to those features identified
     *                   by the filter.  Feature instances can be specified
     *                   explicitly and individually using the identifier of
     *                   each feature instance OR a set of features to be
     *                   operated on can be identified by specifying spatial
     *                   and non-spatial constraints in the filter.
     *                   If no filter is specified then update operation 
     *                   applies to all feature instances.
     *                
     * 
     * @return
     *     possible object is
     *     {@link FilterType }
     *     
     */
    public FilterType getFilter() {
        return filter;
    }

    /**
     * Sets the value of the filter property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilterType }
     *     
     */
    public void setFilter(FilterType value) {
        this.filter = value;
    }

    public boolean isSetFilter() {
        return (this.filter!= null);
    }

    /**
     * Gets the value of the handle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandle() {
        return handle;
    }

    /**
     * Sets the value of the handle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandle(String value) {
        this.handle = value;
    }

    public boolean isSetHandle() {
        return (this.handle!= null);
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setTypeName(QName value) {
        this.typeName = value;
    }

    public boolean isSetTypeName() {
        return (this.typeName!= null);
    }

    /**
     * Gets the value of the inputFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputFormat() {
        if (inputFormat == null) {
            return "x-application/gml:3";
        } else {
            return inputFormat;
        }
    }

    /**
     * Sets the value of the inputFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputFormat(String value) {
        this.inputFormat = value;
    }

    public boolean isSetInputFormat() {
        return (this.inputFormat!= null);
    }

    /**
     * Gets the value of the srsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSrsName() {
        return srsName;
    }

    /**
     * Sets the value of the srsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSrsName(String value) {
        this.srsName = value;
    }

    public boolean isSetSrsName() {
        return (this.srsName!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            List<PropertyType> theProperty;
            theProperty = (this.isSetProperty()?this.getProperty():null);
            strategy.appendField(locator, this, "property", buffer, theProperty, this.isSetProperty());
        }
        {
            FilterType theFilter;
            theFilter = this.getFilter();
            strategy.appendField(locator, this, "filter", buffer, theFilter, this.isSetFilter());
        }
        {
            String theHandle;
            theHandle = this.getHandle();
            strategy.appendField(locator, this, "handle", buffer, theHandle, this.isSetHandle());
        }
        {
            QName theTypeName;
            theTypeName = this.getTypeName();
            strategy.appendField(locator, this, "typeName", buffer, theTypeName, this.isSetTypeName());
        }
        {
            String theInputFormat;
            theInputFormat = this.getInputFormat();
            strategy.appendField(locator, this, "inputFormat", buffer, theInputFormat, this.isSetInputFormat());
        }
        {
            String theSrsName;
            theSrsName = this.getSrsName();
            strategy.appendField(locator, this, "srsName", buffer, theSrsName, this.isSetSrsName());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final UpdateElementType that = ((UpdateElementType) object);
        {
            List<PropertyType> lhsProperty;
            lhsProperty = (this.isSetProperty()?this.getProperty():null);
            List<PropertyType> rhsProperty;
            rhsProperty = (that.isSetProperty()?that.getProperty():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "property", lhsProperty), LocatorUtils.property(thatLocator, "property", rhsProperty), lhsProperty, rhsProperty, this.isSetProperty(), that.isSetProperty())) {
                return false;
            }
        }
        {
            FilterType lhsFilter;
            lhsFilter = this.getFilter();
            FilterType rhsFilter;
            rhsFilter = that.getFilter();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "filter", lhsFilter), LocatorUtils.property(thatLocator, "filter", rhsFilter), lhsFilter, rhsFilter, this.isSetFilter(), that.isSetFilter())) {
                return false;
            }
        }
        {
            String lhsHandle;
            lhsHandle = this.getHandle();
            String rhsHandle;
            rhsHandle = that.getHandle();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "handle", lhsHandle), LocatorUtils.property(thatLocator, "handle", rhsHandle), lhsHandle, rhsHandle, this.isSetHandle(), that.isSetHandle())) {
                return false;
            }
        }
        {
            QName lhsTypeName;
            lhsTypeName = this.getTypeName();
            QName rhsTypeName;
            rhsTypeName = that.getTypeName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "typeName", lhsTypeName), LocatorUtils.property(thatLocator, "typeName", rhsTypeName), lhsTypeName, rhsTypeName, this.isSetTypeName(), that.isSetTypeName())) {
                return false;
            }
        }
        {
            String lhsInputFormat;
            lhsInputFormat = this.getInputFormat();
            String rhsInputFormat;
            rhsInputFormat = that.getInputFormat();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "inputFormat", lhsInputFormat), LocatorUtils.property(thatLocator, "inputFormat", rhsInputFormat), lhsInputFormat, rhsInputFormat, this.isSetInputFormat(), that.isSetInputFormat())) {
                return false;
            }
        }
        {
            String lhsSrsName;
            lhsSrsName = this.getSrsName();
            String rhsSrsName;
            rhsSrsName = that.getSrsName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "srsName", lhsSrsName), LocatorUtils.property(thatLocator, "srsName", rhsSrsName), lhsSrsName, rhsSrsName, this.isSetSrsName(), that.isSetSrsName())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            List<PropertyType> theProperty;
            theProperty = (this.isSetProperty()?this.getProperty():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "property", theProperty), currentHashCode, theProperty, this.isSetProperty());
        }
        {
            FilterType theFilter;
            theFilter = this.getFilter();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "filter", theFilter), currentHashCode, theFilter, this.isSetFilter());
        }
        {
            String theHandle;
            theHandle = this.getHandle();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "handle", theHandle), currentHashCode, theHandle, this.isSetHandle());
        }
        {
            QName theTypeName;
            theTypeName = this.getTypeName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "typeName", theTypeName), currentHashCode, theTypeName, this.isSetTypeName());
        }
        {
            String theInputFormat;
            theInputFormat = this.getInputFormat();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inputFormat", theInputFormat), currentHashCode, theInputFormat, this.isSetInputFormat());
        }
        {
            String theSrsName;
            theSrsName = this.getSrsName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "srsName", theSrsName), currentHashCode, theSrsName, this.isSetSrsName());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof UpdateElementType) {
            final UpdateElementType copy = ((UpdateElementType) draftCopy);
            {
                Boolean propertyShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetProperty());
                if (propertyShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<PropertyType> sourceProperty;
                    sourceProperty = (this.isSetProperty()?this.getProperty():null);
                    @SuppressWarnings("unchecked")
                    List<PropertyType> copyProperty = ((List<PropertyType> ) strategy.copy(LocatorUtils.property(locator, "property", sourceProperty), sourceProperty, this.isSetProperty()));
                    copy.unsetProperty();
                    if (copyProperty!= null) {
                        List<PropertyType> uniquePropertyl = copy.getProperty();
                        uniquePropertyl.addAll(copyProperty);
                    }
                } else {
                    if (propertyShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetProperty();
                    }
                }
            }
            {
                Boolean filterShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetFilter());
                if (filterShouldBeCopiedAndSet == Boolean.TRUE) {
                    FilterType sourceFilter;
                    sourceFilter = this.getFilter();
                    FilterType copyFilter = ((FilterType) strategy.copy(LocatorUtils.property(locator, "filter", sourceFilter), sourceFilter, this.isSetFilter()));
                    copy.setFilter(copyFilter);
                } else {
                    if (filterShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.filter = null;
                    }
                }
            }
            {
                Boolean handleShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetHandle());
                if (handleShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceHandle;
                    sourceHandle = this.getHandle();
                    String copyHandle = ((String) strategy.copy(LocatorUtils.property(locator, "handle", sourceHandle), sourceHandle, this.isSetHandle()));
                    copy.setHandle(copyHandle);
                } else {
                    if (handleShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.handle = null;
                    }
                }
            }
            {
                Boolean typeNameShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetTypeName());
                if (typeNameShouldBeCopiedAndSet == Boolean.TRUE) {
                    QName sourceTypeName;
                    sourceTypeName = this.getTypeName();
                    QName copyTypeName = ((QName) strategy.copy(LocatorUtils.property(locator, "typeName", sourceTypeName), sourceTypeName, this.isSetTypeName()));
                    copy.setTypeName(copyTypeName);
                } else {
                    if (typeNameShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.typeName = null;
                    }
                }
            }
            {
                Boolean inputFormatShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetInputFormat());
                if (inputFormatShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceInputFormat;
                    sourceInputFormat = this.getInputFormat();
                    String copyInputFormat = ((String) strategy.copy(LocatorUtils.property(locator, "inputFormat", sourceInputFormat), sourceInputFormat, this.isSetInputFormat()));
                    copy.setInputFormat(copyInputFormat);
                } else {
                    if (inputFormatShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.inputFormat = null;
                    }
                }
            }
            {
                Boolean srsNameShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetSrsName());
                if (srsNameShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceSrsName;
                    sourceSrsName = this.getSrsName();
                    String copySrsName = ((String) strategy.copy(LocatorUtils.property(locator, "srsName", sourceSrsName), sourceSrsName, this.isSetSrsName()));
                    copy.setSrsName(copySrsName);
                } else {
                    if (srsNameShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.srsName = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new UpdateElementType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        if (right instanceof UpdateElementType) {
            final UpdateElementType target = this;
            final UpdateElementType leftObject = ((UpdateElementType) left);
            final UpdateElementType rightObject = ((UpdateElementType) right);
            {
                Boolean propertyShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetProperty(), rightObject.isSetProperty());
                if (propertyShouldBeMergedAndSet == Boolean.TRUE) {
                    List<PropertyType> lhsProperty;
                    lhsProperty = (leftObject.isSetProperty()?leftObject.getProperty():null);
                    List<PropertyType> rhsProperty;
                    rhsProperty = (rightObject.isSetProperty()?rightObject.getProperty():null);
                    List<PropertyType> mergedProperty = ((List<PropertyType> ) strategy.merge(LocatorUtils.property(leftLocator, "property", lhsProperty), LocatorUtils.property(rightLocator, "property", rhsProperty), lhsProperty, rhsProperty, leftObject.isSetProperty(), rightObject.isSetProperty()));
                    target.unsetProperty();
                    if (mergedProperty!= null) {
                        List<PropertyType> uniquePropertyl = target.getProperty();
                        uniquePropertyl.addAll(mergedProperty);
                    }
                } else {
                    if (propertyShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetProperty();
                    }
                }
            }
            {
                Boolean filterShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetFilter(), rightObject.isSetFilter());
                if (filterShouldBeMergedAndSet == Boolean.TRUE) {
                    FilterType lhsFilter;
                    lhsFilter = leftObject.getFilter();
                    FilterType rhsFilter;
                    rhsFilter = rightObject.getFilter();
                    FilterType mergedFilter = ((FilterType) strategy.merge(LocatorUtils.property(leftLocator, "filter", lhsFilter), LocatorUtils.property(rightLocator, "filter", rhsFilter), lhsFilter, rhsFilter, leftObject.isSetFilter(), rightObject.isSetFilter()));
                    target.setFilter(mergedFilter);
                } else {
                    if (filterShouldBeMergedAndSet == Boolean.FALSE) {
                        target.filter = null;
                    }
                }
            }
            {
                Boolean handleShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetHandle(), rightObject.isSetHandle());
                if (handleShouldBeMergedAndSet == Boolean.TRUE) {
                    String lhsHandle;
                    lhsHandle = leftObject.getHandle();
                    String rhsHandle;
                    rhsHandle = rightObject.getHandle();
                    String mergedHandle = ((String) strategy.merge(LocatorUtils.property(leftLocator, "handle", lhsHandle), LocatorUtils.property(rightLocator, "handle", rhsHandle), lhsHandle, rhsHandle, leftObject.isSetHandle(), rightObject.isSetHandle()));
                    target.setHandle(mergedHandle);
                } else {
                    if (handleShouldBeMergedAndSet == Boolean.FALSE) {
                        target.handle = null;
                    }
                }
            }
            {
                Boolean typeNameShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetTypeName(), rightObject.isSetTypeName());
                if (typeNameShouldBeMergedAndSet == Boolean.TRUE) {
                    QName lhsTypeName;
                    lhsTypeName = leftObject.getTypeName();
                    QName rhsTypeName;
                    rhsTypeName = rightObject.getTypeName();
                    QName mergedTypeName = ((QName) strategy.merge(LocatorUtils.property(leftLocator, "typeName", lhsTypeName), LocatorUtils.property(rightLocator, "typeName", rhsTypeName), lhsTypeName, rhsTypeName, leftObject.isSetTypeName(), rightObject.isSetTypeName()));
                    target.setTypeName(mergedTypeName);
                } else {
                    if (typeNameShouldBeMergedAndSet == Boolean.FALSE) {
                        target.typeName = null;
                    }
                }
            }
            {
                Boolean inputFormatShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetInputFormat(), rightObject.isSetInputFormat());
                if (inputFormatShouldBeMergedAndSet == Boolean.TRUE) {
                    String lhsInputFormat;
                    lhsInputFormat = leftObject.getInputFormat();
                    String rhsInputFormat;
                    rhsInputFormat = rightObject.getInputFormat();
                    String mergedInputFormat = ((String) strategy.merge(LocatorUtils.property(leftLocator, "inputFormat", lhsInputFormat), LocatorUtils.property(rightLocator, "inputFormat", rhsInputFormat), lhsInputFormat, rhsInputFormat, leftObject.isSetInputFormat(), rightObject.isSetInputFormat()));
                    target.setInputFormat(mergedInputFormat);
                } else {
                    if (inputFormatShouldBeMergedAndSet == Boolean.FALSE) {
                        target.inputFormat = null;
                    }
                }
            }
            {
                Boolean srsNameShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetSrsName(), rightObject.isSetSrsName());
                if (srsNameShouldBeMergedAndSet == Boolean.TRUE) {
                    String lhsSrsName;
                    lhsSrsName = leftObject.getSrsName();
                    String rhsSrsName;
                    rhsSrsName = rightObject.getSrsName();
                    String mergedSrsName = ((String) strategy.merge(LocatorUtils.property(leftLocator, "srsName", lhsSrsName), LocatorUtils.property(rightLocator, "srsName", rhsSrsName), lhsSrsName, rhsSrsName, leftObject.isSetSrsName(), rightObject.isSetSrsName()));
                    target.setSrsName(mergedSrsName);
                } else {
                    if (srsNameShouldBeMergedAndSet == Boolean.FALSE) {
                        target.srsName = null;
                    }
                }
            }
        }
    }

    public void setProperty(List<PropertyType> value) {
        this.property = null;
        if (value!= null) {
            List<PropertyType> draftl = this.getProperty();
            draftl.addAll(value);
        }
    }

    public UpdateElementType withProperty(PropertyType... values) {
        if (values!= null) {
            for (PropertyType value: values) {
                getProperty().add(value);
            }
        }
        return this;
    }

    public UpdateElementType withProperty(Collection<PropertyType> values) {
        if (values!= null) {
            getProperty().addAll(values);
        }
        return this;
    }

    public UpdateElementType withFilter(FilterType value) {
        setFilter(value);
        return this;
    }

    public UpdateElementType withHandle(String value) {
        setHandle(value);
        return this;
    }

    public UpdateElementType withTypeName(QName value) {
        setTypeName(value);
        return this;
    }

    public UpdateElementType withInputFormat(String value) {
        setInputFormat(value);
        return this;
    }

    public UpdateElementType withSrsName(String value) {
        setSrsName(value);
        return this;
    }

    public UpdateElementType withProperty(List<PropertyType> value) {
        setProperty(value);
        return this;
    }

}
