//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:47:59 PM AST 
//


package net.opengis.gml.v_3_2_0;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for CompoundCRSType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompoundCRSType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractCRSType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}componentReferenceSystem" maxOccurs="unbounded" minOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://www.opengis.net/gml}AggregationAttributeGroup"/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompoundCRSType", propOrder = {
    "componentReferenceSystem"
})
public class CompoundCRSType
    extends AbstractCRSType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElementRef(name = "componentReferenceSystem", namespace = "http://www.opengis.net/gml", type = JAXBElement.class)
    protected List<JAXBElement<SingleCRSPropertyType>> componentReferenceSystem;
    @XmlAttribute(name = "aggregationType")
    protected AggregationType aggregationType;

    /**
     * Gets the value of the componentReferenceSystem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentReferenceSystem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentReferenceSystem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link SingleCRSPropertyType }{@code >}
     * {@link JAXBElement }{@code <}{@link SingleCRSPropertyType }{@code >}
     * 
     * 
     */
    public List<JAXBElement<SingleCRSPropertyType>> getComponentReferenceSystem() {
        if (componentReferenceSystem == null) {
            componentReferenceSystem = new ArrayList<JAXBElement<SingleCRSPropertyType>>();
        }
        return this.componentReferenceSystem;
    }

    public boolean isSetComponentReferenceSystem() {
        return ((this.componentReferenceSystem!= null)&&(!this.componentReferenceSystem.isEmpty()));
    }

    public void unsetComponentReferenceSystem() {
        this.componentReferenceSystem = null;
    }

    /**
     * Gets the value of the aggregationType property.
     * 
     * @return
     *     possible object is
     *     {@link AggregationType }
     *     
     */
    public AggregationType getAggregationType() {
        return aggregationType;
    }

    /**
     * Sets the value of the aggregationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AggregationType }
     *     
     */
    public void setAggregationType(AggregationType value) {
        this.aggregationType = value;
    }

    public boolean isSetAggregationType() {
        return (this.aggregationType!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<JAXBElement<SingleCRSPropertyType>> theComponentReferenceSystem;
            theComponentReferenceSystem = (this.isSetComponentReferenceSystem()?this.getComponentReferenceSystem():null);
            strategy.appendField(locator, this, "componentReferenceSystem", buffer, theComponentReferenceSystem, this.isSetComponentReferenceSystem());
        }
        {
            AggregationType theAggregationType;
            theAggregationType = this.getAggregationType();
            strategy.appendField(locator, this, "aggregationType", buffer, theAggregationType, this.isSetAggregationType());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final CompoundCRSType that = ((CompoundCRSType) object);
        {
            List<JAXBElement<SingleCRSPropertyType>> lhsComponentReferenceSystem;
            lhsComponentReferenceSystem = (this.isSetComponentReferenceSystem()?this.getComponentReferenceSystem():null);
            List<JAXBElement<SingleCRSPropertyType>> rhsComponentReferenceSystem;
            rhsComponentReferenceSystem = (that.isSetComponentReferenceSystem()?that.getComponentReferenceSystem():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "componentReferenceSystem", lhsComponentReferenceSystem), LocatorUtils.property(thatLocator, "componentReferenceSystem", rhsComponentReferenceSystem), lhsComponentReferenceSystem, rhsComponentReferenceSystem, this.isSetComponentReferenceSystem(), that.isSetComponentReferenceSystem())) {
                return false;
            }
        }
        {
            AggregationType lhsAggregationType;
            lhsAggregationType = this.getAggregationType();
            AggregationType rhsAggregationType;
            rhsAggregationType = that.getAggregationType();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aggregationType", lhsAggregationType), LocatorUtils.property(thatLocator, "aggregationType", rhsAggregationType), lhsAggregationType, rhsAggregationType, this.isSetAggregationType(), that.isSetAggregationType())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<JAXBElement<SingleCRSPropertyType>> theComponentReferenceSystem;
            theComponentReferenceSystem = (this.isSetComponentReferenceSystem()?this.getComponentReferenceSystem():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "componentReferenceSystem", theComponentReferenceSystem), currentHashCode, theComponentReferenceSystem, this.isSetComponentReferenceSystem());
        }
        {
            AggregationType theAggregationType;
            theAggregationType = this.getAggregationType();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aggregationType", theAggregationType), currentHashCode, theAggregationType, this.isSetAggregationType());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof CompoundCRSType) {
            final CompoundCRSType copy = ((CompoundCRSType) draftCopy);
            {
                java.lang.Boolean componentReferenceSystemShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetComponentReferenceSystem());
                if (componentReferenceSystemShouldBeCopiedAndSet == java.lang.Boolean.TRUE) {
                    List<JAXBElement<SingleCRSPropertyType>> sourceComponentReferenceSystem;
                    sourceComponentReferenceSystem = (this.isSetComponentReferenceSystem()?this.getComponentReferenceSystem():null);
                    @SuppressWarnings("unchecked")
                    List<JAXBElement<SingleCRSPropertyType>> copyComponentReferenceSystem = ((List<JAXBElement<SingleCRSPropertyType>> ) strategy.copy(LocatorUtils.property(locator, "componentReferenceSystem", sourceComponentReferenceSystem), sourceComponentReferenceSystem, this.isSetComponentReferenceSystem()));
                    copy.unsetComponentReferenceSystem();
                    if (copyComponentReferenceSystem!= null) {
                        List<JAXBElement<SingleCRSPropertyType>> uniqueComponentReferenceSysteml = copy.getComponentReferenceSystem();
                        uniqueComponentReferenceSysteml.addAll(copyComponentReferenceSystem);
                    }
                } else {
                    if (componentReferenceSystemShouldBeCopiedAndSet == java.lang.Boolean.FALSE) {
                        copy.unsetComponentReferenceSystem();
                    }
                }
            }
            {
                java.lang.Boolean aggregationTypeShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetAggregationType());
                if (aggregationTypeShouldBeCopiedAndSet == java.lang.Boolean.TRUE) {
                    AggregationType sourceAggregationType;
                    sourceAggregationType = this.getAggregationType();
                    AggregationType copyAggregationType = ((AggregationType) strategy.copy(LocatorUtils.property(locator, "aggregationType", sourceAggregationType), sourceAggregationType, this.isSetAggregationType()));
                    copy.setAggregationType(copyAggregationType);
                } else {
                    if (aggregationTypeShouldBeCopiedAndSet == java.lang.Boolean.FALSE) {
                        copy.aggregationType = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new CompoundCRSType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof CompoundCRSType) {
            final CompoundCRSType target = this;
            final CompoundCRSType leftObject = ((CompoundCRSType) left);
            final CompoundCRSType rightObject = ((CompoundCRSType) right);
            {
                java.lang.Boolean componentReferenceSystemShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetComponentReferenceSystem(), rightObject.isSetComponentReferenceSystem());
                if (componentReferenceSystemShouldBeMergedAndSet == java.lang.Boolean.TRUE) {
                    List<JAXBElement<SingleCRSPropertyType>> lhsComponentReferenceSystem;
                    lhsComponentReferenceSystem = (leftObject.isSetComponentReferenceSystem()?leftObject.getComponentReferenceSystem():null);
                    List<JAXBElement<SingleCRSPropertyType>> rhsComponentReferenceSystem;
                    rhsComponentReferenceSystem = (rightObject.isSetComponentReferenceSystem()?rightObject.getComponentReferenceSystem():null);
                    List<JAXBElement<SingleCRSPropertyType>> mergedComponentReferenceSystem = ((List<JAXBElement<SingleCRSPropertyType>> ) strategy.merge(LocatorUtils.property(leftLocator, "componentReferenceSystem", lhsComponentReferenceSystem), LocatorUtils.property(rightLocator, "componentReferenceSystem", rhsComponentReferenceSystem), lhsComponentReferenceSystem, rhsComponentReferenceSystem, leftObject.isSetComponentReferenceSystem(), rightObject.isSetComponentReferenceSystem()));
                    target.unsetComponentReferenceSystem();
                    if (mergedComponentReferenceSystem!= null) {
                        List<JAXBElement<SingleCRSPropertyType>> uniqueComponentReferenceSysteml = target.getComponentReferenceSystem();
                        uniqueComponentReferenceSysteml.addAll(mergedComponentReferenceSystem);
                    }
                } else {
                    if (componentReferenceSystemShouldBeMergedAndSet == java.lang.Boolean.FALSE) {
                        target.unsetComponentReferenceSystem();
                    }
                }
            }
            {
                java.lang.Boolean aggregationTypeShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetAggregationType(), rightObject.isSetAggregationType());
                if (aggregationTypeShouldBeMergedAndSet == java.lang.Boolean.TRUE) {
                    AggregationType lhsAggregationType;
                    lhsAggregationType = leftObject.getAggregationType();
                    AggregationType rhsAggregationType;
                    rhsAggregationType = rightObject.getAggregationType();
                    AggregationType mergedAggregationType = ((AggregationType) strategy.merge(LocatorUtils.property(leftLocator, "aggregationType", lhsAggregationType), LocatorUtils.property(rightLocator, "aggregationType", rhsAggregationType), lhsAggregationType, rhsAggregationType, leftObject.isSetAggregationType(), rightObject.isSetAggregationType()));
                    target.setAggregationType(mergedAggregationType);
                } else {
                    if (aggregationTypeShouldBeMergedAndSet == java.lang.Boolean.FALSE) {
                        target.aggregationType = null;
                    }
                }
            }
        }
    }

    public void setComponentReferenceSystem(List<JAXBElement<SingleCRSPropertyType>> value) {
        this.componentReferenceSystem = null;
        if (value!= null) {
            List<JAXBElement<SingleCRSPropertyType>> draftl = this.getComponentReferenceSystem();
            draftl.addAll(value);
        }
    }

    public CompoundCRSType withComponentReferenceSystem(JAXBElement<SingleCRSPropertyType> ... values) {
        if (values!= null) {
            for (JAXBElement<SingleCRSPropertyType> value: values) {
                getComponentReferenceSystem().add(value);
            }
        }
        return this;
    }

    public CompoundCRSType withComponentReferenceSystem(Collection<JAXBElement<SingleCRSPropertyType>> values) {
        if (values!= null) {
            getComponentReferenceSystem().addAll(values);
        }
        return this;
    }

    public CompoundCRSType withAggregationType(AggregationType value) {
        setAggregationType(value);
        return this;
    }

    public CompoundCRSType withComponentReferenceSystem(List<JAXBElement<SingleCRSPropertyType>> value) {
        setComponentReferenceSystem(value);
        return this;
    }

    @Override
    public CompoundCRSType withDomainOfValidity(DomainOfValidity... values) {
        if (values!= null) {
            for (DomainOfValidity value: values) {
                getDomainOfValidity().add(value);
            }
        }
        return this;
    }

    @Override
    public CompoundCRSType withDomainOfValidity(Collection<DomainOfValidity> values) {
        if (values!= null) {
            getDomainOfValidity().addAll(values);
        }
        return this;
    }

    @Override
    public CompoundCRSType withScope(String... values) {
        if (values!= null) {
            for (String value: values) {
                getScope().add(value);
            }
        }
        return this;
    }

    @Override
    public CompoundCRSType withScope(Collection<String> values) {
        if (values!= null) {
            getScope().addAll(values);
        }
        return this;
    }

    @Override
    public CompoundCRSType withDomainOfValidity(List<DomainOfValidity> value) {
        setDomainOfValidity(value);
        return this;
    }

    @Override
    public CompoundCRSType withScope(List<String> value) {
        setScope(value);
        return this;
    }

    @Override
    public CompoundCRSType withRemarks(String value) {
        setRemarks(value);
        return this;
    }

    @Override
    public CompoundCRSType withMetaDataProperty(MetaDataPropertyType... values) {
        if (values!= null) {
            for (MetaDataPropertyType value: values) {
                getMetaDataProperty().add(value);
            }
        }
        return this;
    }

    @Override
    public CompoundCRSType withMetaDataProperty(Collection<MetaDataPropertyType> values) {
        if (values!= null) {
            getMetaDataProperty().addAll(values);
        }
        return this;
    }

    @Override
    public CompoundCRSType withDescription(StringOrRefType value) {
        setDescription(value);
        return this;
    }

    @Override
    public CompoundCRSType withDescriptionReference(ReferenceType value) {
        setDescriptionReference(value);
        return this;
    }

    @Override
    public CompoundCRSType withIdentifier(CodeWithAuthorityType value) {
        setIdentifier(value);
        return this;
    }

    @Override
    public CompoundCRSType withName(CodeType... values) {
        if (values!= null) {
            for (CodeType value: values) {
                getName().add(value);
            }
        }
        return this;
    }

    @Override
    public CompoundCRSType withName(Collection<CodeType> values) {
        if (values!= null) {
            getName().addAll(values);
        }
        return this;
    }

    @Override
    public CompoundCRSType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public CompoundCRSType withMetaDataProperty(List<MetaDataPropertyType> value) {
        setMetaDataProperty(value);
        return this;
    }

    @Override
    public CompoundCRSType withName(List<CodeType> value) {
        setName(value);
        return this;
    }

}
