//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:47:59 PM AST 
//


package net.opengis.gml.v_3_2_0;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for SolidType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SolidType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml}AbstractSolidType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="exterior" type="{http://www.opengis.net/gml}ShellPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="interior" type="{http://www.opengis.net/gml}ShellPropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SolidType", propOrder = {
    "exterior",
    "interior"
})
public class SolidType
    extends AbstractSolidType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    protected ShellPropertyType exterior;
    protected List<ShellPropertyType> interior;

    /**
     * Gets the value of the exterior property.
     * 
     * @return
     *     possible object is
     *     {@link ShellPropertyType }
     *     
     */
    public ShellPropertyType getExterior() {
        return exterior;
    }

    /**
     * Sets the value of the exterior property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShellPropertyType }
     *     
     */
    public void setExterior(ShellPropertyType value) {
        this.exterior = value;
    }

    public boolean isSetExterior() {
        return (this.exterior!= null);
    }

    /**
     * Gets the value of the interior property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the interior property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInterior().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ShellPropertyType }
     * 
     * 
     */
    public List<ShellPropertyType> getInterior() {
        if (interior == null) {
            interior = new ArrayList<ShellPropertyType>();
        }
        return this.interior;
    }

    public boolean isSetInterior() {
        return ((this.interior!= null)&&(!this.interior.isEmpty()));
    }

    public void unsetInterior() {
        this.interior = null;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            ShellPropertyType theExterior;
            theExterior = this.getExterior();
            strategy.appendField(locator, this, "exterior", buffer, theExterior, this.isSetExterior());
        }
        {
            List<ShellPropertyType> theInterior;
            theInterior = (this.isSetInterior()?this.getInterior():null);
            strategy.appendField(locator, this, "interior", buffer, theInterior, this.isSetInterior());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final SolidType that = ((SolidType) object);
        {
            ShellPropertyType lhsExterior;
            lhsExterior = this.getExterior();
            ShellPropertyType rhsExterior;
            rhsExterior = that.getExterior();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "exterior", lhsExterior), LocatorUtils.property(thatLocator, "exterior", rhsExterior), lhsExterior, rhsExterior, this.isSetExterior(), that.isSetExterior())) {
                return false;
            }
        }
        {
            List<ShellPropertyType> lhsInterior;
            lhsInterior = (this.isSetInterior()?this.getInterior():null);
            List<ShellPropertyType> rhsInterior;
            rhsInterior = (that.isSetInterior()?that.getInterior():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "interior", lhsInterior), LocatorUtils.property(thatLocator, "interior", rhsInterior), lhsInterior, rhsInterior, this.isSetInterior(), that.isSetInterior())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            ShellPropertyType theExterior;
            theExterior = this.getExterior();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "exterior", theExterior), currentHashCode, theExterior, this.isSetExterior());
        }
        {
            List<ShellPropertyType> theInterior;
            theInterior = (this.isSetInterior()?this.getInterior():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "interior", theInterior), currentHashCode, theInterior, this.isSetInterior());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof SolidType) {
            final SolidType copy = ((SolidType) draftCopy);
            {
                java.lang.Boolean exteriorShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetExterior());
                if (exteriorShouldBeCopiedAndSet == java.lang.Boolean.TRUE) {
                    ShellPropertyType sourceExterior;
                    sourceExterior = this.getExterior();
                    ShellPropertyType copyExterior = ((ShellPropertyType) strategy.copy(LocatorUtils.property(locator, "exterior", sourceExterior), sourceExterior, this.isSetExterior()));
                    copy.setExterior(copyExterior);
                } else {
                    if (exteriorShouldBeCopiedAndSet == java.lang.Boolean.FALSE) {
                        copy.exterior = null;
                    }
                }
            }
            {
                java.lang.Boolean interiorShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetInterior());
                if (interiorShouldBeCopiedAndSet == java.lang.Boolean.TRUE) {
                    List<ShellPropertyType> sourceInterior;
                    sourceInterior = (this.isSetInterior()?this.getInterior():null);
                    @SuppressWarnings("unchecked")
                    List<ShellPropertyType> copyInterior = ((List<ShellPropertyType> ) strategy.copy(LocatorUtils.property(locator, "interior", sourceInterior), sourceInterior, this.isSetInterior()));
                    copy.unsetInterior();
                    if (copyInterior!= null) {
                        List<ShellPropertyType> uniqueInteriorl = copy.getInterior();
                        uniqueInteriorl.addAll(copyInterior);
                    }
                } else {
                    if (interiorShouldBeCopiedAndSet == java.lang.Boolean.FALSE) {
                        copy.unsetInterior();
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new SolidType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof SolidType) {
            final SolidType target = this;
            final SolidType leftObject = ((SolidType) left);
            final SolidType rightObject = ((SolidType) right);
            {
                java.lang.Boolean exteriorShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetExterior(), rightObject.isSetExterior());
                if (exteriorShouldBeMergedAndSet == java.lang.Boolean.TRUE) {
                    ShellPropertyType lhsExterior;
                    lhsExterior = leftObject.getExterior();
                    ShellPropertyType rhsExterior;
                    rhsExterior = rightObject.getExterior();
                    ShellPropertyType mergedExterior = ((ShellPropertyType) strategy.merge(LocatorUtils.property(leftLocator, "exterior", lhsExterior), LocatorUtils.property(rightLocator, "exterior", rhsExterior), lhsExterior, rhsExterior, leftObject.isSetExterior(), rightObject.isSetExterior()));
                    target.setExterior(mergedExterior);
                } else {
                    if (exteriorShouldBeMergedAndSet == java.lang.Boolean.FALSE) {
                        target.exterior = null;
                    }
                }
            }
            {
                java.lang.Boolean interiorShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetInterior(), rightObject.isSetInterior());
                if (interiorShouldBeMergedAndSet == java.lang.Boolean.TRUE) {
                    List<ShellPropertyType> lhsInterior;
                    lhsInterior = (leftObject.isSetInterior()?leftObject.getInterior():null);
                    List<ShellPropertyType> rhsInterior;
                    rhsInterior = (rightObject.isSetInterior()?rightObject.getInterior():null);
                    List<ShellPropertyType> mergedInterior = ((List<ShellPropertyType> ) strategy.merge(LocatorUtils.property(leftLocator, "interior", lhsInterior), LocatorUtils.property(rightLocator, "interior", rhsInterior), lhsInterior, rhsInterior, leftObject.isSetInterior(), rightObject.isSetInterior()));
                    target.unsetInterior();
                    if (mergedInterior!= null) {
                        List<ShellPropertyType> uniqueInteriorl = target.getInterior();
                        uniqueInteriorl.addAll(mergedInterior);
                    }
                } else {
                    if (interiorShouldBeMergedAndSet == java.lang.Boolean.FALSE) {
                        target.unsetInterior();
                    }
                }
            }
        }
    }

    public void setInterior(List<ShellPropertyType> value) {
        this.interior = null;
        if (value!= null) {
            List<ShellPropertyType> draftl = this.getInterior();
            draftl.addAll(value);
        }
    }

    public SolidType withExterior(ShellPropertyType value) {
        setExterior(value);
        return this;
    }

    public SolidType withInterior(ShellPropertyType... values) {
        if (values!= null) {
            for (ShellPropertyType value: values) {
                getInterior().add(value);
            }
        }
        return this;
    }

    public SolidType withInterior(Collection<ShellPropertyType> values) {
        if (values!= null) {
            getInterior().addAll(values);
        }
        return this;
    }

    public SolidType withInterior(List<ShellPropertyType> value) {
        setInterior(value);
        return this;
    }

    @Override
    public SolidType withSrsName(String value) {
        setSrsName(value);
        return this;
    }

    @Override
    public SolidType withSrsDimension(BigInteger value) {
        setSrsDimension(value);
        return this;
    }

    @Override
    public SolidType withAxisLabels(String... values) {
        if (values!= null) {
            for (String value: values) {
                getAxisLabels().add(value);
            }
        }
        return this;
    }

    @Override
    public SolidType withAxisLabels(Collection<String> values) {
        if (values!= null) {
            getAxisLabels().addAll(values);
        }
        return this;
    }

    @Override
    public SolidType withUomLabels(String... values) {
        if (values!= null) {
            for (String value: values) {
                getUomLabels().add(value);
            }
        }
        return this;
    }

    @Override
    public SolidType withUomLabels(Collection<String> values) {
        if (values!= null) {
            getUomLabels().addAll(values);
        }
        return this;
    }

    @Override
    public SolidType withAxisLabels(List<String> value) {
        setAxisLabels(value);
        return this;
    }

    @Override
    public SolidType withUomLabels(List<String> value) {
        setUomLabels(value);
        return this;
    }

    @Override
    public SolidType withMetaDataProperty(MetaDataPropertyType... values) {
        if (values!= null) {
            for (MetaDataPropertyType value: values) {
                getMetaDataProperty().add(value);
            }
        }
        return this;
    }

    @Override
    public SolidType withMetaDataProperty(Collection<MetaDataPropertyType> values) {
        if (values!= null) {
            getMetaDataProperty().addAll(values);
        }
        return this;
    }

    @Override
    public SolidType withDescription(StringOrRefType value) {
        setDescription(value);
        return this;
    }

    @Override
    public SolidType withDescriptionReference(ReferenceType value) {
        setDescriptionReference(value);
        return this;
    }

    @Override
    public SolidType withIdentifier(CodeWithAuthorityType value) {
        setIdentifier(value);
        return this;
    }

    @Override
    public SolidType withName(CodeType... values) {
        if (values!= null) {
            for (CodeType value: values) {
                getName().add(value);
            }
        }
        return this;
    }

    @Override
    public SolidType withName(Collection<CodeType> values) {
        if (values!= null) {
            getName().addAll(values);
        }
        return this;
    }

    @Override
    public SolidType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public SolidType withMetaDataProperty(List<MetaDataPropertyType> value) {
        setMetaDataProperty(value);
        return this;
    }

    @Override
    public SolidType withName(List<CodeType> value) {
        setName(value);
        return this;
    }

}
