//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.10 at 03:04:33 PM CET 
//


package org.cuahsi.waterml._1;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2025 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for QualityControlLevelEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="QualityControlLevelEnum"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Raw data"/&gt;
 *     &lt;enumeration value="Quality controlled data"/&gt;
 *     &lt;enumeration value="Derived products"/&gt;
 *     &lt;enumeration value="Interpreted products"/&gt;
 *     &lt;enumeration value="Knowledge products"/&gt;
 *     &lt;enumeration value="Unknown"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "QualityControlLevelEnum")
@XmlEnum
public enum QualityControlLevelEnum {

    @XmlEnumValue("Raw data")
    RAW_DATA("Raw data"),
    @XmlEnumValue("Quality controlled data")
    QUALITY_CONTROLLED_DATA("Quality controlled data"),
    @XmlEnumValue("Derived products")
    DERIVED_PRODUCTS("Derived products"),
    @XmlEnumValue("Interpreted products")
    INTERPRETED_PRODUCTS("Interpreted products"),
    @XmlEnumValue("Knowledge products")
    KNOWLEDGE_PRODUCTS("Knowledge products"),
    @XmlEnumValue("Unknown")
    UNKNOWN("Unknown");
    private final String value;

    QualityControlLevelEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static QualityControlLevelEnum fromValue(String v) {
        for (QualityControlLevelEnum c: QualityControlLevelEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
