//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:54:10 PM AST 
//


package net.opengis.iso19139.gmx.v_20060504;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;
import net.opengis.iso19139.gmd.v_20060504.AbstractDSAggregateType;
import net.opengis.iso19139.gmd.v_20060504.DSAggregatePropertyType;
import net.opengis.iso19139.gmd.v_20060504.DSDataSetPropertyType;
import net.opengis.iso19139.gmd.v_20060504.MDMetadataPropertyType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for MX_Aggregate_Type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MX_Aggregate_Type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.isotc211.org/2005/gmd}AbstractDS_Aggregate_Type"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="aggregateCatalogue" type="{http://www.isotc211.org/2005/gmx}CT_Catalogue_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="aggregateFile" type="{http://www.isotc211.org/2005/gmx}MX_SupportFile_PropertyType" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MX_Aggregate_Type", propOrder = {
    "aggregateCatalogue",
    "aggregateFile"
})
public class MXAggregateType
    extends AbstractDSAggregateType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    protected List<CTCataloguePropertyType> aggregateCatalogue;
    protected List<MXSupportFilePropertyType> aggregateFile;

    /**
     * Gets the value of the aggregateCatalogue property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregateCatalogue property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregateCatalogue().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CTCataloguePropertyType }
     * 
     * 
     */
    public List<CTCataloguePropertyType> getAggregateCatalogue() {
        if (aggregateCatalogue == null) {
            aggregateCatalogue = new ArrayList<CTCataloguePropertyType>();
        }
        return this.aggregateCatalogue;
    }

    public boolean isSetAggregateCatalogue() {
        return ((this.aggregateCatalogue!= null)&&(!this.aggregateCatalogue.isEmpty()));
    }

    public void unsetAggregateCatalogue() {
        this.aggregateCatalogue = null;
    }

    /**
     * Gets the value of the aggregateFile property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the aggregateFile property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAggregateFile().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MXSupportFilePropertyType }
     * 
     * 
     */
    public List<MXSupportFilePropertyType> getAggregateFile() {
        if (aggregateFile == null) {
            aggregateFile = new ArrayList<MXSupportFilePropertyType>();
        }
        return this.aggregateFile;
    }

    public boolean isSetAggregateFile() {
        return ((this.aggregateFile!= null)&&(!this.aggregateFile.isEmpty()));
    }

    public void unsetAggregateFile() {
        this.aggregateFile = null;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<CTCataloguePropertyType> theAggregateCatalogue;
            theAggregateCatalogue = (this.isSetAggregateCatalogue()?this.getAggregateCatalogue():null);
            strategy.appendField(locator, this, "aggregateCatalogue", buffer, theAggregateCatalogue, this.isSetAggregateCatalogue());
        }
        {
            List<MXSupportFilePropertyType> theAggregateFile;
            theAggregateFile = (this.isSetAggregateFile()?this.getAggregateFile():null);
            strategy.appendField(locator, this, "aggregateFile", buffer, theAggregateFile, this.isSetAggregateFile());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final MXAggregateType that = ((MXAggregateType) object);
        {
            List<CTCataloguePropertyType> lhsAggregateCatalogue;
            lhsAggregateCatalogue = (this.isSetAggregateCatalogue()?this.getAggregateCatalogue():null);
            List<CTCataloguePropertyType> rhsAggregateCatalogue;
            rhsAggregateCatalogue = (that.isSetAggregateCatalogue()?that.getAggregateCatalogue():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aggregateCatalogue", lhsAggregateCatalogue), LocatorUtils.property(thatLocator, "aggregateCatalogue", rhsAggregateCatalogue), lhsAggregateCatalogue, rhsAggregateCatalogue, this.isSetAggregateCatalogue(), that.isSetAggregateCatalogue())) {
                return false;
            }
        }
        {
            List<MXSupportFilePropertyType> lhsAggregateFile;
            lhsAggregateFile = (this.isSetAggregateFile()?this.getAggregateFile():null);
            List<MXSupportFilePropertyType> rhsAggregateFile;
            rhsAggregateFile = (that.isSetAggregateFile()?that.getAggregateFile():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "aggregateFile", lhsAggregateFile), LocatorUtils.property(thatLocator, "aggregateFile", rhsAggregateFile), lhsAggregateFile, rhsAggregateFile, this.isSetAggregateFile(), that.isSetAggregateFile())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<CTCataloguePropertyType> theAggregateCatalogue;
            theAggregateCatalogue = (this.isSetAggregateCatalogue()?this.getAggregateCatalogue():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aggregateCatalogue", theAggregateCatalogue), currentHashCode, theAggregateCatalogue, this.isSetAggregateCatalogue());
        }
        {
            List<MXSupportFilePropertyType> theAggregateFile;
            theAggregateFile = (this.isSetAggregateFile()?this.getAggregateFile():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "aggregateFile", theAggregateFile), currentHashCode, theAggregateFile, this.isSetAggregateFile());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof MXAggregateType) {
            final MXAggregateType copy = ((MXAggregateType) draftCopy);
            {
                Boolean aggregateCatalogueShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetAggregateCatalogue());
                if (aggregateCatalogueShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<CTCataloguePropertyType> sourceAggregateCatalogue;
                    sourceAggregateCatalogue = (this.isSetAggregateCatalogue()?this.getAggregateCatalogue():null);
                    @SuppressWarnings("unchecked")
                    List<CTCataloguePropertyType> copyAggregateCatalogue = ((List<CTCataloguePropertyType> ) strategy.copy(LocatorUtils.property(locator, "aggregateCatalogue", sourceAggregateCatalogue), sourceAggregateCatalogue, this.isSetAggregateCatalogue()));
                    copy.unsetAggregateCatalogue();
                    if (copyAggregateCatalogue!= null) {
                        List<CTCataloguePropertyType> uniqueAggregateCataloguel = copy.getAggregateCatalogue();
                        uniqueAggregateCataloguel.addAll(copyAggregateCatalogue);
                    }
                } else {
                    if (aggregateCatalogueShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetAggregateCatalogue();
                    }
                }
            }
            {
                Boolean aggregateFileShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetAggregateFile());
                if (aggregateFileShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<MXSupportFilePropertyType> sourceAggregateFile;
                    sourceAggregateFile = (this.isSetAggregateFile()?this.getAggregateFile():null);
                    @SuppressWarnings("unchecked")
                    List<MXSupportFilePropertyType> copyAggregateFile = ((List<MXSupportFilePropertyType> ) strategy.copy(LocatorUtils.property(locator, "aggregateFile", sourceAggregateFile), sourceAggregateFile, this.isSetAggregateFile()));
                    copy.unsetAggregateFile();
                    if (copyAggregateFile!= null) {
                        List<MXSupportFilePropertyType> uniqueAggregateFilel = copy.getAggregateFile();
                        uniqueAggregateFilel.addAll(copyAggregateFile);
                    }
                } else {
                    if (aggregateFileShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetAggregateFile();
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new MXAggregateType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof MXAggregateType) {
            final MXAggregateType target = this;
            final MXAggregateType leftObject = ((MXAggregateType) left);
            final MXAggregateType rightObject = ((MXAggregateType) right);
            {
                Boolean aggregateCatalogueShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetAggregateCatalogue(), rightObject.isSetAggregateCatalogue());
                if (aggregateCatalogueShouldBeMergedAndSet == Boolean.TRUE) {
                    List<CTCataloguePropertyType> lhsAggregateCatalogue;
                    lhsAggregateCatalogue = (leftObject.isSetAggregateCatalogue()?leftObject.getAggregateCatalogue():null);
                    List<CTCataloguePropertyType> rhsAggregateCatalogue;
                    rhsAggregateCatalogue = (rightObject.isSetAggregateCatalogue()?rightObject.getAggregateCatalogue():null);
                    List<CTCataloguePropertyType> mergedAggregateCatalogue = ((List<CTCataloguePropertyType> ) strategy.merge(LocatorUtils.property(leftLocator, "aggregateCatalogue", lhsAggregateCatalogue), LocatorUtils.property(rightLocator, "aggregateCatalogue", rhsAggregateCatalogue), lhsAggregateCatalogue, rhsAggregateCatalogue, leftObject.isSetAggregateCatalogue(), rightObject.isSetAggregateCatalogue()));
                    target.unsetAggregateCatalogue();
                    if (mergedAggregateCatalogue!= null) {
                        List<CTCataloguePropertyType> uniqueAggregateCataloguel = target.getAggregateCatalogue();
                        uniqueAggregateCataloguel.addAll(mergedAggregateCatalogue);
                    }
                } else {
                    if (aggregateCatalogueShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetAggregateCatalogue();
                    }
                }
            }
            {
                Boolean aggregateFileShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetAggregateFile(), rightObject.isSetAggregateFile());
                if (aggregateFileShouldBeMergedAndSet == Boolean.TRUE) {
                    List<MXSupportFilePropertyType> lhsAggregateFile;
                    lhsAggregateFile = (leftObject.isSetAggregateFile()?leftObject.getAggregateFile():null);
                    List<MXSupportFilePropertyType> rhsAggregateFile;
                    rhsAggregateFile = (rightObject.isSetAggregateFile()?rightObject.getAggregateFile():null);
                    List<MXSupportFilePropertyType> mergedAggregateFile = ((List<MXSupportFilePropertyType> ) strategy.merge(LocatorUtils.property(leftLocator, "aggregateFile", lhsAggregateFile), LocatorUtils.property(rightLocator, "aggregateFile", rhsAggregateFile), lhsAggregateFile, rhsAggregateFile, leftObject.isSetAggregateFile(), rightObject.isSetAggregateFile()));
                    target.unsetAggregateFile();
                    if (mergedAggregateFile!= null) {
                        List<MXSupportFilePropertyType> uniqueAggregateFilel = target.getAggregateFile();
                        uniqueAggregateFilel.addAll(mergedAggregateFile);
                    }
                } else {
                    if (aggregateFileShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetAggregateFile();
                    }
                }
            }
        }
    }

    public void setAggregateCatalogue(List<CTCataloguePropertyType> value) {
        this.aggregateCatalogue = null;
        if (value!= null) {
            List<CTCataloguePropertyType> draftl = this.getAggregateCatalogue();
            draftl.addAll(value);
        }
    }

    public void setAggregateFile(List<MXSupportFilePropertyType> value) {
        this.aggregateFile = null;
        if (value!= null) {
            List<MXSupportFilePropertyType> draftl = this.getAggregateFile();
            draftl.addAll(value);
        }
    }

    public MXAggregateType withAggregateCatalogue(CTCataloguePropertyType... values) {
        if (values!= null) {
            for (CTCataloguePropertyType value: values) {
                getAggregateCatalogue().add(value);
            }
        }
        return this;
    }

    public MXAggregateType withAggregateCatalogue(Collection<CTCataloguePropertyType> values) {
        if (values!= null) {
            getAggregateCatalogue().addAll(values);
        }
        return this;
    }

    public MXAggregateType withAggregateFile(MXSupportFilePropertyType... values) {
        if (values!= null) {
            for (MXSupportFilePropertyType value: values) {
                getAggregateFile().add(value);
            }
        }
        return this;
    }

    public MXAggregateType withAggregateFile(Collection<MXSupportFilePropertyType> values) {
        if (values!= null) {
            getAggregateFile().addAll(values);
        }
        return this;
    }

    public MXAggregateType withAggregateCatalogue(List<CTCataloguePropertyType> value) {
        setAggregateCatalogue(value);
        return this;
    }

    public MXAggregateType withAggregateFile(List<MXSupportFilePropertyType> value) {
        setAggregateFile(value);
        return this;
    }

    @Override
    public MXAggregateType withComposedOf(DSDataSetPropertyType... values) {
        if (values!= null) {
            for (DSDataSetPropertyType value: values) {
                getComposedOf().add(value);
            }
        }
        return this;
    }

    @Override
    public MXAggregateType withComposedOf(Collection<DSDataSetPropertyType> values) {
        if (values!= null) {
            getComposedOf().addAll(values);
        }
        return this;
    }

    @Override
    public MXAggregateType withSeriesMetadata(MDMetadataPropertyType... values) {
        if (values!= null) {
            for (MDMetadataPropertyType value: values) {
                getSeriesMetadata().add(value);
            }
        }
        return this;
    }

    @Override
    public MXAggregateType withSeriesMetadata(Collection<MDMetadataPropertyType> values) {
        if (values!= null) {
            getSeriesMetadata().addAll(values);
        }
        return this;
    }

    @Override
    public MXAggregateType withSubset(DSAggregatePropertyType... values) {
        if (values!= null) {
            for (DSAggregatePropertyType value: values) {
                getSubset().add(value);
            }
        }
        return this;
    }

    @Override
    public MXAggregateType withSubset(Collection<DSAggregatePropertyType> values) {
        if (values!= null) {
            getSubset().addAll(values);
        }
        return this;
    }

    @Override
    public MXAggregateType withSuperset(DSAggregatePropertyType... values) {
        if (values!= null) {
            for (DSAggregatePropertyType value: values) {
                getSuperset().add(value);
            }
        }
        return this;
    }

    @Override
    public MXAggregateType withSuperset(Collection<DSAggregatePropertyType> values) {
        if (values!= null) {
            getSuperset().addAll(values);
        }
        return this;
    }

    @Override
    public MXAggregateType withComposedOf(List<DSDataSetPropertyType> value) {
        setComposedOf(value);
        return this;
    }

    @Override
    public MXAggregateType withSeriesMetadata(List<MDMetadataPropertyType> value) {
        setSeriesMetadata(value);
        return this;
    }

    @Override
    public MXAggregateType withSubset(List<DSAggregatePropertyType> value) {
        setSubset(value);
        return this;
    }

    @Override
    public MXAggregateType withSuperset(List<DSAggregatePropertyType> value) {
        setSuperset(value);
        return this;
    }

    @Override
    public MXAggregateType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public MXAggregateType withUuid(String value) {
        setUuid(value);
        return this;
    }

}
