//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:46:02 PM AST 
//


package net.opengis.swecommon.v_2_0;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for DataArrayPropertyByValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DataArrayPropertyByValueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/swe/2.0}DataArray"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DataArrayPropertyByValueType", propOrder = {
    "dataArray"
})
public class DataArrayPropertyByValueType implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElementRef(name = "DataArray", namespace = "http://www.opengis.net/swe/2.0", type = JAXBElement.class)
    protected JAXBElement<? extends DataArrayType> dataArray;

    /**
     * Gets the value of the dataArray property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link MatrixType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataArrayType }{@code >}
     *     
     */
    public JAXBElement<? extends DataArrayType> getDataArray() {
        return dataArray;
    }

    /**
     * Sets the value of the dataArray property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link MatrixType }{@code >}
     *     {@link JAXBElement }{@code <}{@link DataArrayType }{@code >}
     *     
     */
    public void setDataArray(JAXBElement<? extends DataArrayType> value) {
        this.dataArray = value;
    }

    public boolean isSetDataArray() {
        return (this.dataArray!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            JAXBElement<? extends DataArrayType> theDataArray;
            theDataArray = this.getDataArray();
            strategy.appendField(locator, this, "dataArray", buffer, theDataArray, this.isSetDataArray());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final DataArrayPropertyByValueType that = ((DataArrayPropertyByValueType) object);
        {
            JAXBElement<? extends DataArrayType> lhsDataArray;
            lhsDataArray = this.getDataArray();
            JAXBElement<? extends DataArrayType> rhsDataArray;
            rhsDataArray = that.getDataArray();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "dataArray", lhsDataArray), LocatorUtils.property(thatLocator, "dataArray", rhsDataArray), lhsDataArray, rhsDataArray, this.isSetDataArray(), that.isSetDataArray())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            JAXBElement<? extends DataArrayType> theDataArray;
            theDataArray = this.getDataArray();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "dataArray", theDataArray), currentHashCode, theDataArray, this.isSetDataArray());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof DataArrayPropertyByValueType) {
            final DataArrayPropertyByValueType copy = ((DataArrayPropertyByValueType) draftCopy);
            {
                Boolean dataArrayShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetDataArray());
                if (dataArrayShouldBeCopiedAndSet == Boolean.TRUE) {
                    JAXBElement<? extends DataArrayType> sourceDataArray;
                    sourceDataArray = this.getDataArray();
                    @SuppressWarnings("unchecked")
                    JAXBElement<? extends DataArrayType> copyDataArray = ((JAXBElement<? extends DataArrayType> ) strategy.copy(LocatorUtils.property(locator, "dataArray", sourceDataArray), sourceDataArray, this.isSetDataArray()));
                    copy.setDataArray(copyDataArray);
                } else {
                    if (dataArrayShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.dataArray = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new DataArrayPropertyByValueType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        if (right instanceof DataArrayPropertyByValueType) {
            final DataArrayPropertyByValueType target = this;
            final DataArrayPropertyByValueType leftObject = ((DataArrayPropertyByValueType) left);
            final DataArrayPropertyByValueType rightObject = ((DataArrayPropertyByValueType) right);
            {
                Boolean dataArrayShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetDataArray(), rightObject.isSetDataArray());
                if (dataArrayShouldBeMergedAndSet == Boolean.TRUE) {
                    JAXBElement<? extends DataArrayType> lhsDataArray;
                    lhsDataArray = leftObject.getDataArray();
                    JAXBElement<? extends DataArrayType> rhsDataArray;
                    rhsDataArray = rightObject.getDataArray();
                    JAXBElement<? extends DataArrayType> mergedDataArray = ((JAXBElement<? extends DataArrayType> ) strategy.merge(LocatorUtils.property(leftLocator, "dataArray", lhsDataArray), LocatorUtils.property(rightLocator, "dataArray", rhsDataArray), lhsDataArray, rhsDataArray, leftObject.isSetDataArray(), rightObject.isSetDataArray()));
                    target.setDataArray(mergedDataArray);
                } else {
                    if (dataArrayShouldBeMergedAndSet == Boolean.FALSE) {
                        target.dataArray = null;
                    }
                }
            }
        }
    }

    public DataArrayPropertyByValueType withDataArray(JAXBElement<? extends DataArrayType> value) {
        setDataArray(value);
        return this;
    }

}
