//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:46:02 PM AST 
//


package net.opengis.swecommon.v_2_0;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for XMLEncodingPropertyByValueType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="XMLEncodingPropertyByValueType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/swe/2.0}XMLEncoding"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "XMLEncodingPropertyByValueType", propOrder = {
    "xmlEncoding"
})
public class XMLEncodingPropertyByValueType implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElement(name = "XMLEncoding", required = true)
    protected XMLEncodingType xmlEncoding;

    /**
     * Gets the value of the xmlEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link XMLEncodingType }
     *     
     */
    public XMLEncodingType getXMLEncoding() {
        return xmlEncoding;
    }

    /**
     * Sets the value of the xmlEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLEncodingType }
     *     
     */
    public void setXMLEncoding(XMLEncodingType value) {
        this.xmlEncoding = value;
    }

    public boolean isSetXMLEncoding() {
        return (this.xmlEncoding!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            XMLEncodingType theXMLEncoding;
            theXMLEncoding = this.getXMLEncoding();
            strategy.appendField(locator, this, "xmlEncoding", buffer, theXMLEncoding, this.isSetXMLEncoding());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final XMLEncodingPropertyByValueType that = ((XMLEncodingPropertyByValueType) object);
        {
            XMLEncodingType lhsXMLEncoding;
            lhsXMLEncoding = this.getXMLEncoding();
            XMLEncodingType rhsXMLEncoding;
            rhsXMLEncoding = that.getXMLEncoding();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "xmlEncoding", lhsXMLEncoding), LocatorUtils.property(thatLocator, "xmlEncoding", rhsXMLEncoding), lhsXMLEncoding, rhsXMLEncoding, this.isSetXMLEncoding(), that.isSetXMLEncoding())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            XMLEncodingType theXMLEncoding;
            theXMLEncoding = this.getXMLEncoding();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "xmlEncoding", theXMLEncoding), currentHashCode, theXMLEncoding, this.isSetXMLEncoding());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof XMLEncodingPropertyByValueType) {
            final XMLEncodingPropertyByValueType copy = ((XMLEncodingPropertyByValueType) draftCopy);
            {
                Boolean xmlEncodingShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetXMLEncoding());
                if (xmlEncodingShouldBeCopiedAndSet == Boolean.TRUE) {
                    XMLEncodingType sourceXMLEncoding;
                    sourceXMLEncoding = this.getXMLEncoding();
                    XMLEncodingType copyXMLEncoding = ((XMLEncodingType) strategy.copy(LocatorUtils.property(locator, "xmlEncoding", sourceXMLEncoding), sourceXMLEncoding, this.isSetXMLEncoding()));
                    copy.setXMLEncoding(copyXMLEncoding);
                } else {
                    if (xmlEncodingShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.xmlEncoding = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new XMLEncodingPropertyByValueType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        if (right instanceof XMLEncodingPropertyByValueType) {
            final XMLEncodingPropertyByValueType target = this;
            final XMLEncodingPropertyByValueType leftObject = ((XMLEncodingPropertyByValueType) left);
            final XMLEncodingPropertyByValueType rightObject = ((XMLEncodingPropertyByValueType) right);
            {
                Boolean xmlEncodingShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetXMLEncoding(), rightObject.isSetXMLEncoding());
                if (xmlEncodingShouldBeMergedAndSet == Boolean.TRUE) {
                    XMLEncodingType lhsXMLEncoding;
                    lhsXMLEncoding = leftObject.getXMLEncoding();
                    XMLEncodingType rhsXMLEncoding;
                    rhsXMLEncoding = rightObject.getXMLEncoding();
                    XMLEncodingType mergedXMLEncoding = ((XMLEncodingType) strategy.merge(LocatorUtils.property(leftLocator, "xmlEncoding", lhsXMLEncoding), LocatorUtils.property(rightLocator, "xmlEncoding", rhsXMLEncoding), lhsXMLEncoding, rhsXMLEncoding, leftObject.isSetXMLEncoding(), rightObject.isSetXMLEncoding()));
                    target.setXMLEncoding(mergedXMLEncoding);
                } else {
                    if (xmlEncodingShouldBeMergedAndSet == Boolean.FALSE) {
                        target.xmlEncoding = null;
                    }
                }
            }
        }
    }

    public XMLEncodingPropertyByValueType withXMLEncoding(XMLEncodingType value) {
        setXMLEncoding(value);
        return this;
    }

}
