PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?concept ?prefLabel ?altLabel ?close
WHERE 
{
  ${CONCEPT_URI} skos:broader ?concept .
  
  ?concept skos:closeMatch* ?concept1.
  OPTIONAL {?concept skos:closeMatch* ?close}.
  ?concept skos:prefLabel ?prefLabel. 
  OPTIONAL { ?concept skos:altLabel ?altLabel } 
 
}
LIMIT 1000

