//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:04:25 PM AST 
//


package net.opengis.sensorml.v_2_0;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_0.ReferenceType;
import net.opengis.iso19139.gmd.v_20060504.MDLegalConstraintsPropertyType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for AbstractProcessType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractProcessType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/sensorml/2.0}DescribedObjectType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="typeOf" type="{http://www.opengis.net/gml/3.2}ReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="configuration" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}AbstractSettings"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="featuresOfInterest" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}FeatureList"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="inputs" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}InputList"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="outputs" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}OutputList"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="parameters" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}ParameterList"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="modes" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}AbstractModes"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="definition" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractProcessType", propOrder = {
    "typeOf",
    "configuration",
    "featuresOfInterest",
    "inputs",
    "outputs",
    "parameters",
    "modes"
})
@XmlSeeAlso({
    SimpleProcessType.class,
    AggregateProcessType.class,
    AbstractPhysicalProcessType.class
})
public abstract class AbstractProcessType
    extends DescribedObjectType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    protected ReferenceType typeOf;
    protected Configuration configuration;
    protected FeaturesOfInterest featuresOfInterest;
    protected Inputs inputs;
    protected Outputs outputs;
    protected Parameters parameters;
    protected List<Modes> modes;
    @XmlAttribute(name = "definition")
    @XmlSchemaType(name = "anyURI")
    protected String definition;

    /**
     * Gets the value of the typeOf property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getTypeOf() {
        return typeOf;
    }

    /**
     * Sets the value of the typeOf property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setTypeOf(ReferenceType value) {
        this.typeOf = value;
    }

    public boolean isSetTypeOf() {
        return (this.typeOf!= null);
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link Configuration }
     *     
     */
    public Configuration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Configuration }
     *     
     */
    public void setConfiguration(Configuration value) {
        this.configuration = value;
    }

    public boolean isSetConfiguration() {
        return (this.configuration!= null);
    }

    /**
     * Gets the value of the featuresOfInterest property.
     * 
     * @return
     *     possible object is
     *     {@link FeaturesOfInterest }
     *     
     */
    public FeaturesOfInterest getFeaturesOfInterest() {
        return featuresOfInterest;
    }

    /**
     * Sets the value of the featuresOfInterest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeaturesOfInterest }
     *     
     */
    public void setFeaturesOfInterest(FeaturesOfInterest value) {
        this.featuresOfInterest = value;
    }

    public boolean isSetFeaturesOfInterest() {
        return (this.featuresOfInterest!= null);
    }

    /**
     * Gets the value of the inputs property.
     * 
     * @return
     *     possible object is
     *     {@link Inputs }
     *     
     */
    public Inputs getInputs() {
        return inputs;
    }

    /**
     * Sets the value of the inputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Inputs }
     *     
     */
    public void setInputs(Inputs value) {
        this.inputs = value;
    }

    public boolean isSetInputs() {
        return (this.inputs!= null);
    }

    /**
     * Gets the value of the outputs property.
     * 
     * @return
     *     possible object is
     *     {@link Outputs }
     *     
     */
    public Outputs getOutputs() {
        return outputs;
    }

    /**
     * Sets the value of the outputs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Outputs }
     *     
     */
    public void setOutputs(Outputs value) {
        this.outputs = value;
    }

    public boolean isSetOutputs() {
        return (this.outputs!= null);
    }

    /**
     * Gets the value of the parameters property.
     * 
     * @return
     *     possible object is
     *     {@link Parameters }
     *     
     */
    public Parameters getParameters() {
        return parameters;
    }

    /**
     * Sets the value of the parameters property.
     * 
     * @param value
     *     allowed object is
     *     {@link Parameters }
     *     
     */
    public void setParameters(Parameters value) {
        this.parameters = value;
    }

    public boolean isSetParameters() {
        return (this.parameters!= null);
    }

    /**
     * Gets the value of the modes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the modes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getModes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Modes }
     * 
     * 
     */
    public List<Modes> getModes() {
        if (modes == null) {
            modes = new ArrayList<Modes>();
        }
        return this.modes;
    }

    public boolean isSetModes() {
        return ((this.modes!= null)&&(!this.modes.isEmpty()));
    }

    public void unsetModes() {
        this.modes = null;
    }

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefinition() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefinition(String value) {
        this.definition = value;
    }

    public boolean isSetDefinition() {
        return (this.definition!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            ReferenceType theTypeOf;
            theTypeOf = this.getTypeOf();
            strategy.appendField(locator, this, "typeOf", buffer, theTypeOf, this.isSetTypeOf());
        }
        {
            Configuration theConfiguration;
            theConfiguration = this.getConfiguration();
            strategy.appendField(locator, this, "configuration", buffer, theConfiguration, this.isSetConfiguration());
        }
        {
            FeaturesOfInterest theFeaturesOfInterest;
            theFeaturesOfInterest = this.getFeaturesOfInterest();
            strategy.appendField(locator, this, "featuresOfInterest", buffer, theFeaturesOfInterest, this.isSetFeaturesOfInterest());
        }
        {
            Inputs theInputs;
            theInputs = this.getInputs();
            strategy.appendField(locator, this, "inputs", buffer, theInputs, this.isSetInputs());
        }
        {
            Outputs theOutputs;
            theOutputs = this.getOutputs();
            strategy.appendField(locator, this, "outputs", buffer, theOutputs, this.isSetOutputs());
        }
        {
            Parameters theParameters;
            theParameters = this.getParameters();
            strategy.appendField(locator, this, "parameters", buffer, theParameters, this.isSetParameters());
        }
        {
            List<Modes> theModes;
            theModes = (this.isSetModes()?this.getModes():null);
            strategy.appendField(locator, this, "modes", buffer, theModes, this.isSetModes());
        }
        {
            String theDefinition;
            theDefinition = this.getDefinition();
            strategy.appendField(locator, this, "definition", buffer, theDefinition, this.isSetDefinition());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final AbstractProcessType that = ((AbstractProcessType) object);
        {
            ReferenceType lhsTypeOf;
            lhsTypeOf = this.getTypeOf();
            ReferenceType rhsTypeOf;
            rhsTypeOf = that.getTypeOf();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "typeOf", lhsTypeOf), LocatorUtils.property(thatLocator, "typeOf", rhsTypeOf), lhsTypeOf, rhsTypeOf, this.isSetTypeOf(), that.isSetTypeOf())) {
                return false;
            }
        }
        {
            Configuration lhsConfiguration;
            lhsConfiguration = this.getConfiguration();
            Configuration rhsConfiguration;
            rhsConfiguration = that.getConfiguration();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "configuration", lhsConfiguration), LocatorUtils.property(thatLocator, "configuration", rhsConfiguration), lhsConfiguration, rhsConfiguration, this.isSetConfiguration(), that.isSetConfiguration())) {
                return false;
            }
        }
        {
            FeaturesOfInterest lhsFeaturesOfInterest;
            lhsFeaturesOfInterest = this.getFeaturesOfInterest();
            FeaturesOfInterest rhsFeaturesOfInterest;
            rhsFeaturesOfInterest = that.getFeaturesOfInterest();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "featuresOfInterest", lhsFeaturesOfInterest), LocatorUtils.property(thatLocator, "featuresOfInterest", rhsFeaturesOfInterest), lhsFeaturesOfInterest, rhsFeaturesOfInterest, this.isSetFeaturesOfInterest(), that.isSetFeaturesOfInterest())) {
                return false;
            }
        }
        {
            Inputs lhsInputs;
            lhsInputs = this.getInputs();
            Inputs rhsInputs;
            rhsInputs = that.getInputs();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "inputs", lhsInputs), LocatorUtils.property(thatLocator, "inputs", rhsInputs), lhsInputs, rhsInputs, this.isSetInputs(), that.isSetInputs())) {
                return false;
            }
        }
        {
            Outputs lhsOutputs;
            lhsOutputs = this.getOutputs();
            Outputs rhsOutputs;
            rhsOutputs = that.getOutputs();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "outputs", lhsOutputs), LocatorUtils.property(thatLocator, "outputs", rhsOutputs), lhsOutputs, rhsOutputs, this.isSetOutputs(), that.isSetOutputs())) {
                return false;
            }
        }
        {
            Parameters lhsParameters;
            lhsParameters = this.getParameters();
            Parameters rhsParameters;
            rhsParameters = that.getParameters();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "parameters", lhsParameters), LocatorUtils.property(thatLocator, "parameters", rhsParameters), lhsParameters, rhsParameters, this.isSetParameters(), that.isSetParameters())) {
                return false;
            }
        }
        {
            List<Modes> lhsModes;
            lhsModes = (this.isSetModes()?this.getModes():null);
            List<Modes> rhsModes;
            rhsModes = (that.isSetModes()?that.getModes():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "modes", lhsModes), LocatorUtils.property(thatLocator, "modes", rhsModes), lhsModes, rhsModes, this.isSetModes(), that.isSetModes())) {
                return false;
            }
        }
        {
            String lhsDefinition;
            lhsDefinition = this.getDefinition();
            String rhsDefinition;
            rhsDefinition = that.getDefinition();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "definition", lhsDefinition), LocatorUtils.property(thatLocator, "definition", rhsDefinition), lhsDefinition, rhsDefinition, this.isSetDefinition(), that.isSetDefinition())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            ReferenceType theTypeOf;
            theTypeOf = this.getTypeOf();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "typeOf", theTypeOf), currentHashCode, theTypeOf, this.isSetTypeOf());
        }
        {
            Configuration theConfiguration;
            theConfiguration = this.getConfiguration();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "configuration", theConfiguration), currentHashCode, theConfiguration, this.isSetConfiguration());
        }
        {
            FeaturesOfInterest theFeaturesOfInterest;
            theFeaturesOfInterest = this.getFeaturesOfInterest();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "featuresOfInterest", theFeaturesOfInterest), currentHashCode, theFeaturesOfInterest, this.isSetFeaturesOfInterest());
        }
        {
            Inputs theInputs;
            theInputs = this.getInputs();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inputs", theInputs), currentHashCode, theInputs, this.isSetInputs());
        }
        {
            Outputs theOutputs;
            theOutputs = this.getOutputs();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "outputs", theOutputs), currentHashCode, theOutputs, this.isSetOutputs());
        }
        {
            Parameters theParameters;
            theParameters = this.getParameters();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "parameters", theParameters), currentHashCode, theParameters, this.isSetParameters());
        }
        {
            List<Modes> theModes;
            theModes = (this.isSetModes()?this.getModes():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "modes", theModes), currentHashCode, theModes, this.isSetModes());
        }
        {
            String theDefinition;
            theDefinition = this.getDefinition();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "definition", theDefinition), currentHashCode, theDefinition, this.isSetDefinition());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        if (null == target) {
            throw new IllegalArgumentException("Target argument must not be null for abstract copyable classes.");
        }
        super.copyTo(locator, target, strategy);
        if (target instanceof AbstractProcessType) {
            final AbstractProcessType copy = ((AbstractProcessType) target);
            {
                Boolean typeOfShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetTypeOf());
                if (typeOfShouldBeCopiedAndSet == Boolean.TRUE) {
                    ReferenceType sourceTypeOf;
                    sourceTypeOf = this.getTypeOf();
                    ReferenceType copyTypeOf = ((ReferenceType) strategy.copy(LocatorUtils.property(locator, "typeOf", sourceTypeOf), sourceTypeOf, this.isSetTypeOf()));
                    copy.setTypeOf(copyTypeOf);
                } else {
                    if (typeOfShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.typeOf = null;
                    }
                }
            }
            {
                Boolean configurationShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetConfiguration());
                if (configurationShouldBeCopiedAndSet == Boolean.TRUE) {
                    Configuration sourceConfiguration;
                    sourceConfiguration = this.getConfiguration();
                    Configuration copyConfiguration = ((Configuration) strategy.copy(LocatorUtils.property(locator, "configuration", sourceConfiguration), sourceConfiguration, this.isSetConfiguration()));
                    copy.setConfiguration(copyConfiguration);
                } else {
                    if (configurationShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.configuration = null;
                    }
                }
            }
            {
                Boolean featuresOfInterestShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetFeaturesOfInterest());
                if (featuresOfInterestShouldBeCopiedAndSet == Boolean.TRUE) {
                    FeaturesOfInterest sourceFeaturesOfInterest;
                    sourceFeaturesOfInterest = this.getFeaturesOfInterest();
                    FeaturesOfInterest copyFeaturesOfInterest = ((FeaturesOfInterest) strategy.copy(LocatorUtils.property(locator, "featuresOfInterest", sourceFeaturesOfInterest), sourceFeaturesOfInterest, this.isSetFeaturesOfInterest()));
                    copy.setFeaturesOfInterest(copyFeaturesOfInterest);
                } else {
                    if (featuresOfInterestShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.featuresOfInterest = null;
                    }
                }
            }
            {
                Boolean inputsShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetInputs());
                if (inputsShouldBeCopiedAndSet == Boolean.TRUE) {
                    Inputs sourceInputs;
                    sourceInputs = this.getInputs();
                    Inputs copyInputs = ((Inputs) strategy.copy(LocatorUtils.property(locator, "inputs", sourceInputs), sourceInputs, this.isSetInputs()));
                    copy.setInputs(copyInputs);
                } else {
                    if (inputsShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.inputs = null;
                    }
                }
            }
            {
                Boolean outputsShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetOutputs());
                if (outputsShouldBeCopiedAndSet == Boolean.TRUE) {
                    Outputs sourceOutputs;
                    sourceOutputs = this.getOutputs();
                    Outputs copyOutputs = ((Outputs) strategy.copy(LocatorUtils.property(locator, "outputs", sourceOutputs), sourceOutputs, this.isSetOutputs()));
                    copy.setOutputs(copyOutputs);
                } else {
                    if (outputsShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.outputs = null;
                    }
                }
            }
            {
                Boolean parametersShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetParameters());
                if (parametersShouldBeCopiedAndSet == Boolean.TRUE) {
                    Parameters sourceParameters;
                    sourceParameters = this.getParameters();
                    Parameters copyParameters = ((Parameters) strategy.copy(LocatorUtils.property(locator, "parameters", sourceParameters), sourceParameters, this.isSetParameters()));
                    copy.setParameters(copyParameters);
                } else {
                    if (parametersShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.parameters = null;
                    }
                }
            }
            {
                Boolean modesShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetModes());
                if (modesShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<Modes> sourceModes;
                    sourceModes = (this.isSetModes()?this.getModes():null);
                    @SuppressWarnings("unchecked")
                    List<Modes> copyModes = ((List<Modes> ) strategy.copy(LocatorUtils.property(locator, "modes", sourceModes), sourceModes, this.isSetModes()));
                    copy.unsetModes();
                    if (copyModes!= null) {
                        List<Modes> uniqueModesl = copy.getModes();
                        uniqueModesl.addAll(copyModes);
                    }
                } else {
                    if (modesShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetModes();
                    }
                }
            }
            {
                Boolean definitionShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetDefinition());
                if (definitionShouldBeCopiedAndSet == Boolean.TRUE) {
                    String sourceDefinition;
                    sourceDefinition = this.getDefinition();
                    String copyDefinition = ((String) strategy.copy(LocatorUtils.property(locator, "definition", sourceDefinition), sourceDefinition, this.isSetDefinition()));
                    copy.setDefinition(copyDefinition);
                } else {
                    if (definitionShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.definition = null;
                    }
                }
            }
        }
        return target;
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof AbstractProcessType) {
            final AbstractProcessType target = this;
            final AbstractProcessType leftObject = ((AbstractProcessType) left);
            final AbstractProcessType rightObject = ((AbstractProcessType) right);
            {
                Boolean typeOfShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetTypeOf(), rightObject.isSetTypeOf());
                if (typeOfShouldBeMergedAndSet == Boolean.TRUE) {
                    ReferenceType lhsTypeOf;
                    lhsTypeOf = leftObject.getTypeOf();
                    ReferenceType rhsTypeOf;
                    rhsTypeOf = rightObject.getTypeOf();
                    ReferenceType mergedTypeOf = ((ReferenceType) strategy.merge(LocatorUtils.property(leftLocator, "typeOf", lhsTypeOf), LocatorUtils.property(rightLocator, "typeOf", rhsTypeOf), lhsTypeOf, rhsTypeOf, leftObject.isSetTypeOf(), rightObject.isSetTypeOf()));
                    target.setTypeOf(mergedTypeOf);
                } else {
                    if (typeOfShouldBeMergedAndSet == Boolean.FALSE) {
                        target.typeOf = null;
                    }
                }
            }
            {
                Boolean configurationShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetConfiguration(), rightObject.isSetConfiguration());
                if (configurationShouldBeMergedAndSet == Boolean.TRUE) {
                    Configuration lhsConfiguration;
                    lhsConfiguration = leftObject.getConfiguration();
                    Configuration rhsConfiguration;
                    rhsConfiguration = rightObject.getConfiguration();
                    Configuration mergedConfiguration = ((Configuration) strategy.merge(LocatorUtils.property(leftLocator, "configuration", lhsConfiguration), LocatorUtils.property(rightLocator, "configuration", rhsConfiguration), lhsConfiguration, rhsConfiguration, leftObject.isSetConfiguration(), rightObject.isSetConfiguration()));
                    target.setConfiguration(mergedConfiguration);
                } else {
                    if (configurationShouldBeMergedAndSet == Boolean.FALSE) {
                        target.configuration = null;
                    }
                }
            }
            {
                Boolean featuresOfInterestShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetFeaturesOfInterest(), rightObject.isSetFeaturesOfInterest());
                if (featuresOfInterestShouldBeMergedAndSet == Boolean.TRUE) {
                    FeaturesOfInterest lhsFeaturesOfInterest;
                    lhsFeaturesOfInterest = leftObject.getFeaturesOfInterest();
                    FeaturesOfInterest rhsFeaturesOfInterest;
                    rhsFeaturesOfInterest = rightObject.getFeaturesOfInterest();
                    FeaturesOfInterest mergedFeaturesOfInterest = ((FeaturesOfInterest) strategy.merge(LocatorUtils.property(leftLocator, "featuresOfInterest", lhsFeaturesOfInterest), LocatorUtils.property(rightLocator, "featuresOfInterest", rhsFeaturesOfInterest), lhsFeaturesOfInterest, rhsFeaturesOfInterest, leftObject.isSetFeaturesOfInterest(), rightObject.isSetFeaturesOfInterest()));
                    target.setFeaturesOfInterest(mergedFeaturesOfInterest);
                } else {
                    if (featuresOfInterestShouldBeMergedAndSet == Boolean.FALSE) {
                        target.featuresOfInterest = null;
                    }
                }
            }
            {
                Boolean inputsShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetInputs(), rightObject.isSetInputs());
                if (inputsShouldBeMergedAndSet == Boolean.TRUE) {
                    Inputs lhsInputs;
                    lhsInputs = leftObject.getInputs();
                    Inputs rhsInputs;
                    rhsInputs = rightObject.getInputs();
                    Inputs mergedInputs = ((Inputs) strategy.merge(LocatorUtils.property(leftLocator, "inputs", lhsInputs), LocatorUtils.property(rightLocator, "inputs", rhsInputs), lhsInputs, rhsInputs, leftObject.isSetInputs(), rightObject.isSetInputs()));
                    target.setInputs(mergedInputs);
                } else {
                    if (inputsShouldBeMergedAndSet == Boolean.FALSE) {
                        target.inputs = null;
                    }
                }
            }
            {
                Boolean outputsShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetOutputs(), rightObject.isSetOutputs());
                if (outputsShouldBeMergedAndSet == Boolean.TRUE) {
                    Outputs lhsOutputs;
                    lhsOutputs = leftObject.getOutputs();
                    Outputs rhsOutputs;
                    rhsOutputs = rightObject.getOutputs();
                    Outputs mergedOutputs = ((Outputs) strategy.merge(LocatorUtils.property(leftLocator, "outputs", lhsOutputs), LocatorUtils.property(rightLocator, "outputs", rhsOutputs), lhsOutputs, rhsOutputs, leftObject.isSetOutputs(), rightObject.isSetOutputs()));
                    target.setOutputs(mergedOutputs);
                } else {
                    if (outputsShouldBeMergedAndSet == Boolean.FALSE) {
                        target.outputs = null;
                    }
                }
            }
            {
                Boolean parametersShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetParameters(), rightObject.isSetParameters());
                if (parametersShouldBeMergedAndSet == Boolean.TRUE) {
                    Parameters lhsParameters;
                    lhsParameters = leftObject.getParameters();
                    Parameters rhsParameters;
                    rhsParameters = rightObject.getParameters();
                    Parameters mergedParameters = ((Parameters) strategy.merge(LocatorUtils.property(leftLocator, "parameters", lhsParameters), LocatorUtils.property(rightLocator, "parameters", rhsParameters), lhsParameters, rhsParameters, leftObject.isSetParameters(), rightObject.isSetParameters()));
                    target.setParameters(mergedParameters);
                } else {
                    if (parametersShouldBeMergedAndSet == Boolean.FALSE) {
                        target.parameters = null;
                    }
                }
            }
            {
                Boolean modesShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetModes(), rightObject.isSetModes());
                if (modesShouldBeMergedAndSet == Boolean.TRUE) {
                    List<Modes> lhsModes;
                    lhsModes = (leftObject.isSetModes()?leftObject.getModes():null);
                    List<Modes> rhsModes;
                    rhsModes = (rightObject.isSetModes()?rightObject.getModes():null);
                    List<Modes> mergedModes = ((List<Modes> ) strategy.merge(LocatorUtils.property(leftLocator, "modes", lhsModes), LocatorUtils.property(rightLocator, "modes", rhsModes), lhsModes, rhsModes, leftObject.isSetModes(), rightObject.isSetModes()));
                    target.unsetModes();
                    if (mergedModes!= null) {
                        List<Modes> uniqueModesl = target.getModes();
                        uniqueModesl.addAll(mergedModes);
                    }
                } else {
                    if (modesShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetModes();
                    }
                }
            }
            {
                Boolean definitionShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetDefinition(), rightObject.isSetDefinition());
                if (definitionShouldBeMergedAndSet == Boolean.TRUE) {
                    String lhsDefinition;
                    lhsDefinition = leftObject.getDefinition();
                    String rhsDefinition;
                    rhsDefinition = rightObject.getDefinition();
                    String mergedDefinition = ((String) strategy.merge(LocatorUtils.property(leftLocator, "definition", lhsDefinition), LocatorUtils.property(rightLocator, "definition", rhsDefinition), lhsDefinition, rhsDefinition, leftObject.isSetDefinition(), rightObject.isSetDefinition()));
                    target.setDefinition(mergedDefinition);
                } else {
                    if (definitionShouldBeMergedAndSet == Boolean.FALSE) {
                        target.definition = null;
                    }
                }
            }
        }
    }

    public void setModes(List<Modes> value) {
        this.modes = null;
        if (value!= null) {
            List<Modes> draftl = this.getModes();
            draftl.addAll(value);
        }
    }

    public AbstractProcessType withTypeOf(ReferenceType value) {
        setTypeOf(value);
        return this;
    }

    public AbstractProcessType withConfiguration(Configuration value) {
        setConfiguration(value);
        return this;
    }

    public AbstractProcessType withFeaturesOfInterest(FeaturesOfInterest value) {
        setFeaturesOfInterest(value);
        return this;
    }

    public AbstractProcessType withInputs(Inputs value) {
        setInputs(value);
        return this;
    }

    public AbstractProcessType withOutputs(Outputs value) {
        setOutputs(value);
        return this;
    }

    public AbstractProcessType withParameters(Parameters value) {
        setParameters(value);
        return this;
    }

    public AbstractProcessType withModes(Modes... values) {
        if (values!= null) {
            for (Modes value: values) {
                getModes().add(value);
            }
        }
        return this;
    }

    public AbstractProcessType withModes(Collection<Modes> values) {
        if (values!= null) {
            getModes().addAll(values);
        }
        return this;
    }

    public AbstractProcessType withDefinition(String value) {
        setDefinition(value);
        return this;
    }

    public AbstractProcessType withModes(List<Modes> value) {
        setModes(value);
        return this;
    }

    @Override
    public AbstractProcessType withExtension(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getExtension().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withExtension(Collection<Object> values) {
        if (values!= null) {
            getExtension().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withKeywords(KeywordListPropertyType... values) {
        if (values!= null) {
            for (KeywordListPropertyType value: values) {
                getKeywords().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withKeywords(Collection<KeywordListPropertyType> values) {
        if (values!= null) {
            getKeywords().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withIdentification(IdentifierListPropertyType... values) {
        if (values!= null) {
            for (IdentifierListPropertyType value: values) {
                getIdentification().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withIdentification(Collection<IdentifierListPropertyType> values) {
        if (values!= null) {
            getIdentification().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withClassification(ClassifierListPropertyType... values) {
        if (values!= null) {
            for (ClassifierListPropertyType value: values) {
                getClassification().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withClassification(Collection<ClassifierListPropertyType> values) {
        if (values!= null) {
            getClassification().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withValidTime(ValidTime... values) {
        if (values!= null) {
            for (ValidTime value: values) {
                getValidTime().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withValidTime(Collection<ValidTime> values) {
        if (values!= null) {
            getValidTime().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withSecurityConstraints(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getSecurityConstraints().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withSecurityConstraints(Collection<Object> values) {
        if (values!= null) {
            getSecurityConstraints().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withLegalConstraints(MDLegalConstraintsPropertyType... values) {
        if (values!= null) {
            for (MDLegalConstraintsPropertyType value: values) {
                getLegalConstraints().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withLegalConstraints(Collection<MDLegalConstraintsPropertyType> values) {
        if (values!= null) {
            getLegalConstraints().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withCharacteristics(Characteristics... values) {
        if (values!= null) {
            for (Characteristics value: values) {
                getCharacteristics().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withCharacteristics(Collection<Characteristics> values) {
        if (values!= null) {
            getCharacteristics().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withCapabilities(Capabilities... values) {
        if (values!= null) {
            for (Capabilities value: values) {
                getCapabilities().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withCapabilities(Collection<Capabilities> values) {
        if (values!= null) {
            getCapabilities().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withContacts(ContactListPropertyType... values) {
        if (values!= null) {
            for (ContactListPropertyType value: values) {
                getContacts().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withContacts(Collection<ContactListPropertyType> values) {
        if (values!= null) {
            getContacts().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withDocumentation(DocumentListPropertyType... values) {
        if (values!= null) {
            for (DocumentListPropertyType value: values) {
                getDocumentation().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withDocumentation(Collection<DocumentListPropertyType> values) {
        if (values!= null) {
            getDocumentation().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withHistory(EventListPropertyType... values) {
        if (values!= null) {
            for (EventListPropertyType value: values) {
                getHistory().add(value);
            }
        }
        return this;
    }

    @Override
    public AbstractProcessType withHistory(Collection<EventListPropertyType> values) {
        if (values!= null) {
            getHistory().addAll(values);
        }
        return this;
    }

    @Override
    public AbstractProcessType withLang(String value) {
        setLang(value);
        return this;
    }

    @Override
    public AbstractProcessType withExtension(List<Object> value) {
        setExtension(value);
        return this;
    }

    @Override
    public AbstractProcessType withKeywords(List<KeywordListPropertyType> value) {
        setKeywords(value);
        return this;
    }

    @Override
    public AbstractProcessType withIdentification(List<IdentifierListPropertyType> value) {
        setIdentification(value);
        return this;
    }

    @Override
    public AbstractProcessType withClassification(List<ClassifierListPropertyType> value) {
        setClassification(value);
        return this;
    }

    @Override
    public AbstractProcessType withValidTime(List<ValidTime> value) {
        setValidTime(value);
        return this;
    }

    @Override
    public AbstractProcessType withSecurityConstraints(List<Object> value) {
        setSecurityConstraints(value);
        return this;
    }

    @Override
    public AbstractProcessType withLegalConstraints(List<MDLegalConstraintsPropertyType> value) {
        setLegalConstraints(value);
        return this;
    }

    @Override
    public AbstractProcessType withCharacteristics(List<Characteristics> value) {
        setCharacteristics(value);
        return this;
    }

    @Override
    public AbstractProcessType withCapabilities(List<Capabilities> value) {
        setCapabilities(value);
        return this;
    }

    @Override
    public AbstractProcessType withContacts(List<ContactListPropertyType> value) {
        setContacts(value);
        return this;
    }

    @Override
    public AbstractProcessType withDocumentation(List<DocumentListPropertyType> value) {
        setDocumentation(value);
        return this;
    }

    @Override
    public AbstractProcessType withHistory(List<EventListPropertyType> value) {
        setHistory(value);
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}AbstractSettings"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractSettings"
    })
    public static class Configuration implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElementRef(name = "AbstractSettings", namespace = "http://www.opengis.net/sensorml/2.0", type = JAXBElement.class)
        protected JAXBElement<? extends AbstractSettingsType> abstractSettings;

        /**
         * Gets the value of the abstractSettings property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link SettingsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AbstractSettingsType }{@code >}
         *     
         */
        public JAXBElement<? extends AbstractSettingsType> getAbstractSettings() {
            return abstractSettings;
        }

        /**
         * Sets the value of the abstractSettings property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link SettingsType }{@code >}
         *     {@link JAXBElement }{@code <}{@link AbstractSettingsType }{@code >}
         *     
         */
        public void setAbstractSettings(JAXBElement<? extends AbstractSettingsType> value) {
            this.abstractSettings = value;
        }

        public boolean isSetAbstractSettings() {
            return (this.abstractSettings!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                JAXBElement<? extends AbstractSettingsType> theAbstractSettings;
                theAbstractSettings = this.getAbstractSettings();
                strategy.appendField(locator, this, "abstractSettings", buffer, theAbstractSettings, this.isSetAbstractSettings());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Configuration that = ((Configuration) object);
            {
                JAXBElement<? extends AbstractSettingsType> lhsAbstractSettings;
                lhsAbstractSettings = this.getAbstractSettings();
                JAXBElement<? extends AbstractSettingsType> rhsAbstractSettings;
                rhsAbstractSettings = that.getAbstractSettings();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "abstractSettings", lhsAbstractSettings), LocatorUtils.property(thatLocator, "abstractSettings", rhsAbstractSettings), lhsAbstractSettings, rhsAbstractSettings, this.isSetAbstractSettings(), that.isSetAbstractSettings())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                JAXBElement<? extends AbstractSettingsType> theAbstractSettings;
                theAbstractSettings = this.getAbstractSettings();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "abstractSettings", theAbstractSettings), currentHashCode, theAbstractSettings, this.isSetAbstractSettings());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Configuration) {
                final Configuration copy = ((Configuration) draftCopy);
                {
                    Boolean abstractSettingsShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetAbstractSettings());
                    if (abstractSettingsShouldBeCopiedAndSet == Boolean.TRUE) {
                        JAXBElement<? extends AbstractSettingsType> sourceAbstractSettings;
                        sourceAbstractSettings = this.getAbstractSettings();
                        @SuppressWarnings("unchecked")
                        JAXBElement<? extends AbstractSettingsType> copyAbstractSettings = ((JAXBElement<? extends AbstractSettingsType> ) strategy.copy(LocatorUtils.property(locator, "abstractSettings", sourceAbstractSettings), sourceAbstractSettings, this.isSetAbstractSettings()));
                        copy.setAbstractSettings(copyAbstractSettings);
                    } else {
                        if (abstractSettingsShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.abstractSettings = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Configuration();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Configuration) {
                final Configuration target = this;
                final Configuration leftObject = ((Configuration) left);
                final Configuration rightObject = ((Configuration) right);
                {
                    Boolean abstractSettingsShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetAbstractSettings(), rightObject.isSetAbstractSettings());
                    if (abstractSettingsShouldBeMergedAndSet == Boolean.TRUE) {
                        JAXBElement<? extends AbstractSettingsType> lhsAbstractSettings;
                        lhsAbstractSettings = leftObject.getAbstractSettings();
                        JAXBElement<? extends AbstractSettingsType> rhsAbstractSettings;
                        rhsAbstractSettings = rightObject.getAbstractSettings();
                        JAXBElement<? extends AbstractSettingsType> mergedAbstractSettings = ((JAXBElement<? extends AbstractSettingsType> ) strategy.merge(LocatorUtils.property(leftLocator, "abstractSettings", lhsAbstractSettings), LocatorUtils.property(rightLocator, "abstractSettings", rhsAbstractSettings), lhsAbstractSettings, rhsAbstractSettings, leftObject.isSetAbstractSettings(), rightObject.isSetAbstractSettings()));
                        target.setAbstractSettings(mergedAbstractSettings);
                    } else {
                        if (abstractSettingsShouldBeMergedAndSet == Boolean.FALSE) {
                            target.abstractSettings = null;
                        }
                    }
                }
            }
        }

        public Configuration withAbstractSettings(JAXBElement<? extends AbstractSettingsType> value) {
            setAbstractSettings(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}FeatureList"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "featureList"
    })
    public static class FeaturesOfInterest implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElement(name = "FeatureList", required = true)
        protected FeatureListType featureList;

        /**
         * Gets the value of the featureList property.
         * 
         * @return
         *     possible object is
         *     {@link FeatureListType }
         *     
         */
        public FeatureListType getFeatureList() {
            return featureList;
        }

        /**
         * Sets the value of the featureList property.
         * 
         * @param value
         *     allowed object is
         *     {@link FeatureListType }
         *     
         */
        public void setFeatureList(FeatureListType value) {
            this.featureList = value;
        }

        public boolean isSetFeatureList() {
            return (this.featureList!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                FeatureListType theFeatureList;
                theFeatureList = this.getFeatureList();
                strategy.appendField(locator, this, "featureList", buffer, theFeatureList, this.isSetFeatureList());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final FeaturesOfInterest that = ((FeaturesOfInterest) object);
            {
                FeatureListType lhsFeatureList;
                lhsFeatureList = this.getFeatureList();
                FeatureListType rhsFeatureList;
                rhsFeatureList = that.getFeatureList();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "featureList", lhsFeatureList), LocatorUtils.property(thatLocator, "featureList", rhsFeatureList), lhsFeatureList, rhsFeatureList, this.isSetFeatureList(), that.isSetFeatureList())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                FeatureListType theFeatureList;
                theFeatureList = this.getFeatureList();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "featureList", theFeatureList), currentHashCode, theFeatureList, this.isSetFeatureList());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof FeaturesOfInterest) {
                final FeaturesOfInterest copy = ((FeaturesOfInterest) draftCopy);
                {
                    Boolean featureListShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetFeatureList());
                    if (featureListShouldBeCopiedAndSet == Boolean.TRUE) {
                        FeatureListType sourceFeatureList;
                        sourceFeatureList = this.getFeatureList();
                        FeatureListType copyFeatureList = ((FeatureListType) strategy.copy(LocatorUtils.property(locator, "featureList", sourceFeatureList), sourceFeatureList, this.isSetFeatureList()));
                        copy.setFeatureList(copyFeatureList);
                    } else {
                        if (featureListShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.featureList = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new FeaturesOfInterest();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof FeaturesOfInterest) {
                final FeaturesOfInterest target = this;
                final FeaturesOfInterest leftObject = ((FeaturesOfInterest) left);
                final FeaturesOfInterest rightObject = ((FeaturesOfInterest) right);
                {
                    Boolean featureListShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetFeatureList(), rightObject.isSetFeatureList());
                    if (featureListShouldBeMergedAndSet == Boolean.TRUE) {
                        FeatureListType lhsFeatureList;
                        lhsFeatureList = leftObject.getFeatureList();
                        FeatureListType rhsFeatureList;
                        rhsFeatureList = rightObject.getFeatureList();
                        FeatureListType mergedFeatureList = ((FeatureListType) strategy.merge(LocatorUtils.property(leftLocator, "featureList", lhsFeatureList), LocatorUtils.property(rightLocator, "featureList", rhsFeatureList), lhsFeatureList, rhsFeatureList, leftObject.isSetFeatureList(), rightObject.isSetFeatureList()));
                        target.setFeatureList(mergedFeatureList);
                    } else {
                        if (featureListShouldBeMergedAndSet == Boolean.FALSE) {
                            target.featureList = null;
                        }
                    }
                }
            }
        }

        public FeaturesOfInterest withFeatureList(FeatureListType value) {
            setFeatureList(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}InputList"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "inputList"
    })
    public static class Inputs implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElement(name = "InputList", required = true)
        protected InputListType inputList;

        /**
         * Gets the value of the inputList property.
         * 
         * @return
         *     possible object is
         *     {@link InputListType }
         *     
         */
        public InputListType getInputList() {
            return inputList;
        }

        /**
         * Sets the value of the inputList property.
         * 
         * @param value
         *     allowed object is
         *     {@link InputListType }
         *     
         */
        public void setInputList(InputListType value) {
            this.inputList = value;
        }

        public boolean isSetInputList() {
            return (this.inputList!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                InputListType theInputList;
                theInputList = this.getInputList();
                strategy.appendField(locator, this, "inputList", buffer, theInputList, this.isSetInputList());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Inputs that = ((Inputs) object);
            {
                InputListType lhsInputList;
                lhsInputList = this.getInputList();
                InputListType rhsInputList;
                rhsInputList = that.getInputList();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "inputList", lhsInputList), LocatorUtils.property(thatLocator, "inputList", rhsInputList), lhsInputList, rhsInputList, this.isSetInputList(), that.isSetInputList())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                InputListType theInputList;
                theInputList = this.getInputList();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "inputList", theInputList), currentHashCode, theInputList, this.isSetInputList());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Inputs) {
                final Inputs copy = ((Inputs) draftCopy);
                {
                    Boolean inputListShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetInputList());
                    if (inputListShouldBeCopiedAndSet == Boolean.TRUE) {
                        InputListType sourceInputList;
                        sourceInputList = this.getInputList();
                        InputListType copyInputList = ((InputListType) strategy.copy(LocatorUtils.property(locator, "inputList", sourceInputList), sourceInputList, this.isSetInputList()));
                        copy.setInputList(copyInputList);
                    } else {
                        if (inputListShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.inputList = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Inputs();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Inputs) {
                final Inputs target = this;
                final Inputs leftObject = ((Inputs) left);
                final Inputs rightObject = ((Inputs) right);
                {
                    Boolean inputListShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetInputList(), rightObject.isSetInputList());
                    if (inputListShouldBeMergedAndSet == Boolean.TRUE) {
                        InputListType lhsInputList;
                        lhsInputList = leftObject.getInputList();
                        InputListType rhsInputList;
                        rhsInputList = rightObject.getInputList();
                        InputListType mergedInputList = ((InputListType) strategy.merge(LocatorUtils.property(leftLocator, "inputList", lhsInputList), LocatorUtils.property(rightLocator, "inputList", rhsInputList), lhsInputList, rhsInputList, leftObject.isSetInputList(), rightObject.isSetInputList()));
                        target.setInputList(mergedInputList);
                    } else {
                        if (inputListShouldBeMergedAndSet == Boolean.FALSE) {
                            target.inputList = null;
                        }
                    }
                }
            }
        }

        public Inputs withInputList(InputListType value) {
            setInputList(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}AbstractModes"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "abstractModes"
    })
    public static class Modes implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElementRef(name = "AbstractModes", namespace = "http://www.opengis.net/sensorml/2.0", type = JAXBElement.class)
        protected JAXBElement<? extends AbstractModesType> abstractModes;

        /**
         * Gets the value of the abstractModes property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link AbstractModesType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ModeChoiceType }{@code >}
         *     
         */
        public JAXBElement<? extends AbstractModesType> getAbstractModes() {
            return abstractModes;
        }

        /**
         * Sets the value of the abstractModes property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link AbstractModesType }{@code >}
         *     {@link JAXBElement }{@code <}{@link ModeChoiceType }{@code >}
         *     
         */
        public void setAbstractModes(JAXBElement<? extends AbstractModesType> value) {
            this.abstractModes = value;
        }

        public boolean isSetAbstractModes() {
            return (this.abstractModes!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                JAXBElement<? extends AbstractModesType> theAbstractModes;
                theAbstractModes = this.getAbstractModes();
                strategy.appendField(locator, this, "abstractModes", buffer, theAbstractModes, this.isSetAbstractModes());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Modes that = ((Modes) object);
            {
                JAXBElement<? extends AbstractModesType> lhsAbstractModes;
                lhsAbstractModes = this.getAbstractModes();
                JAXBElement<? extends AbstractModesType> rhsAbstractModes;
                rhsAbstractModes = that.getAbstractModes();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "abstractModes", lhsAbstractModes), LocatorUtils.property(thatLocator, "abstractModes", rhsAbstractModes), lhsAbstractModes, rhsAbstractModes, this.isSetAbstractModes(), that.isSetAbstractModes())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                JAXBElement<? extends AbstractModesType> theAbstractModes;
                theAbstractModes = this.getAbstractModes();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "abstractModes", theAbstractModes), currentHashCode, theAbstractModes, this.isSetAbstractModes());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Modes) {
                final Modes copy = ((Modes) draftCopy);
                {
                    Boolean abstractModesShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetAbstractModes());
                    if (abstractModesShouldBeCopiedAndSet == Boolean.TRUE) {
                        JAXBElement<? extends AbstractModesType> sourceAbstractModes;
                        sourceAbstractModes = this.getAbstractModes();
                        @SuppressWarnings("unchecked")
                        JAXBElement<? extends AbstractModesType> copyAbstractModes = ((JAXBElement<? extends AbstractModesType> ) strategy.copy(LocatorUtils.property(locator, "abstractModes", sourceAbstractModes), sourceAbstractModes, this.isSetAbstractModes()));
                        copy.setAbstractModes(copyAbstractModes);
                    } else {
                        if (abstractModesShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.abstractModes = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Modes();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Modes) {
                final Modes target = this;
                final Modes leftObject = ((Modes) left);
                final Modes rightObject = ((Modes) right);
                {
                    Boolean abstractModesShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetAbstractModes(), rightObject.isSetAbstractModes());
                    if (abstractModesShouldBeMergedAndSet == Boolean.TRUE) {
                        JAXBElement<? extends AbstractModesType> lhsAbstractModes;
                        lhsAbstractModes = leftObject.getAbstractModes();
                        JAXBElement<? extends AbstractModesType> rhsAbstractModes;
                        rhsAbstractModes = rightObject.getAbstractModes();
                        JAXBElement<? extends AbstractModesType> mergedAbstractModes = ((JAXBElement<? extends AbstractModesType> ) strategy.merge(LocatorUtils.property(leftLocator, "abstractModes", lhsAbstractModes), LocatorUtils.property(rightLocator, "abstractModes", rhsAbstractModes), lhsAbstractModes, rhsAbstractModes, leftObject.isSetAbstractModes(), rightObject.isSetAbstractModes()));
                        target.setAbstractModes(mergedAbstractModes);
                    } else {
                        if (abstractModesShouldBeMergedAndSet == Boolean.FALSE) {
                            target.abstractModes = null;
                        }
                    }
                }
            }
        }

        public Modes withAbstractModes(JAXBElement<? extends AbstractModesType> value) {
            setAbstractModes(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}OutputList"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outputList"
    })
    public static class Outputs implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElement(name = "OutputList", required = true)
        protected OutputListType outputList;

        /**
         * Gets the value of the outputList property.
         * 
         * @return
         *     possible object is
         *     {@link OutputListType }
         *     
         */
        public OutputListType getOutputList() {
            return outputList;
        }

        /**
         * Sets the value of the outputList property.
         * 
         * @param value
         *     allowed object is
         *     {@link OutputListType }
         *     
         */
        public void setOutputList(OutputListType value) {
            this.outputList = value;
        }

        public boolean isSetOutputList() {
            return (this.outputList!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                OutputListType theOutputList;
                theOutputList = this.getOutputList();
                strategy.appendField(locator, this, "outputList", buffer, theOutputList, this.isSetOutputList());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Outputs that = ((Outputs) object);
            {
                OutputListType lhsOutputList;
                lhsOutputList = this.getOutputList();
                OutputListType rhsOutputList;
                rhsOutputList = that.getOutputList();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "outputList", lhsOutputList), LocatorUtils.property(thatLocator, "outputList", rhsOutputList), lhsOutputList, rhsOutputList, this.isSetOutputList(), that.isSetOutputList())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                OutputListType theOutputList;
                theOutputList = this.getOutputList();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "outputList", theOutputList), currentHashCode, theOutputList, this.isSetOutputList());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Outputs) {
                final Outputs copy = ((Outputs) draftCopy);
                {
                    Boolean outputListShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetOutputList());
                    if (outputListShouldBeCopiedAndSet == Boolean.TRUE) {
                        OutputListType sourceOutputList;
                        sourceOutputList = this.getOutputList();
                        OutputListType copyOutputList = ((OutputListType) strategy.copy(LocatorUtils.property(locator, "outputList", sourceOutputList), sourceOutputList, this.isSetOutputList()));
                        copy.setOutputList(copyOutputList);
                    } else {
                        if (outputListShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.outputList = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Outputs();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Outputs) {
                final Outputs target = this;
                final Outputs leftObject = ((Outputs) left);
                final Outputs rightObject = ((Outputs) right);
                {
                    Boolean outputListShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetOutputList(), rightObject.isSetOutputList());
                    if (outputListShouldBeMergedAndSet == Boolean.TRUE) {
                        OutputListType lhsOutputList;
                        lhsOutputList = leftObject.getOutputList();
                        OutputListType rhsOutputList;
                        rhsOutputList = rightObject.getOutputList();
                        OutputListType mergedOutputList = ((OutputListType) strategy.merge(LocatorUtils.property(leftLocator, "outputList", lhsOutputList), LocatorUtils.property(rightLocator, "outputList", rhsOutputList), lhsOutputList, rhsOutputList, leftObject.isSetOutputList(), rightObject.isSetOutputList()));
                        target.setOutputList(mergedOutputList);
                    } else {
                        if (outputListShouldBeMergedAndSet == Boolean.FALSE) {
                            target.outputList = null;
                        }
                    }
                }
            }
        }

        public Outputs withOutputList(OutputListType value) {
            setOutputList(value);
            return this;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}ParameterList"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "parameterList"
    })
    public static class Parameters implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElement(name = "ParameterList", required = true)
        protected ParameterListType parameterList;

        /**
         * Gets the value of the parameterList property.
         * 
         * @return
         *     possible object is
         *     {@link ParameterListType }
         *     
         */
        public ParameterListType getParameterList() {
            return parameterList;
        }

        /**
         * Sets the value of the parameterList property.
         * 
         * @param value
         *     allowed object is
         *     {@link ParameterListType }
         *     
         */
        public void setParameterList(ParameterListType value) {
            this.parameterList = value;
        }

        public boolean isSetParameterList() {
            return (this.parameterList!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                ParameterListType theParameterList;
                theParameterList = this.getParameterList();
                strategy.appendField(locator, this, "parameterList", buffer, theParameterList, this.isSetParameterList());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Parameters that = ((Parameters) object);
            {
                ParameterListType lhsParameterList;
                lhsParameterList = this.getParameterList();
                ParameterListType rhsParameterList;
                rhsParameterList = that.getParameterList();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "parameterList", lhsParameterList), LocatorUtils.property(thatLocator, "parameterList", rhsParameterList), lhsParameterList, rhsParameterList, this.isSetParameterList(), that.isSetParameterList())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                ParameterListType theParameterList;
                theParameterList = this.getParameterList();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "parameterList", theParameterList), currentHashCode, theParameterList, this.isSetParameterList());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Parameters) {
                final Parameters copy = ((Parameters) draftCopy);
                {
                    Boolean parameterListShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetParameterList());
                    if (parameterListShouldBeCopiedAndSet == Boolean.TRUE) {
                        ParameterListType sourceParameterList;
                        sourceParameterList = this.getParameterList();
                        ParameterListType copyParameterList = ((ParameterListType) strategy.copy(LocatorUtils.property(locator, "parameterList", sourceParameterList), sourceParameterList, this.isSetParameterList()));
                        copy.setParameterList(copyParameterList);
                    } else {
                        if (parameterListShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.parameterList = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Parameters();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Parameters) {
                final Parameters target = this;
                final Parameters leftObject = ((Parameters) left);
                final Parameters rightObject = ((Parameters) right);
                {
                    Boolean parameterListShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetParameterList(), rightObject.isSetParameterList());
                    if (parameterListShouldBeMergedAndSet == Boolean.TRUE) {
                        ParameterListType lhsParameterList;
                        lhsParameterList = leftObject.getParameterList();
                        ParameterListType rhsParameterList;
                        rhsParameterList = rightObject.getParameterList();
                        ParameterListType mergedParameterList = ((ParameterListType) strategy.merge(LocatorUtils.property(leftLocator, "parameterList", lhsParameterList), LocatorUtils.property(rightLocator, "parameterList", rhsParameterList), lhsParameterList, rhsParameterList, leftObject.isSetParameterList(), rightObject.isSetParameterList()));
                        target.setParameterList(mergedParameterList);
                    } else {
                        if (parameterListShouldBeMergedAndSet == Boolean.FALSE) {
                            target.parameterList = null;
                        }
                    }
                }
            }
        }

        public Parameters withParameterList(ParameterListType value) {
            setParameterList(value);
            return this;
        }

    }

}
