//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 05:04:25 PM AST 
//


package net.opengis.sensorml.v_2_0;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ClassifierListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassifierListType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/sensorml/2.0}AbstractMetadataListType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="classifier" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element ref="{http://www.opengis.net/sensorml/2.0}Term"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassifierListType", propOrder = {
    "classifier"
})
public class ClassifierListType
    extends AbstractMetadataListType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    @XmlElement(required = true)
    protected List<Classifier> classifier;

    /**
     * Gets the value of the classifier property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classifier property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassifier().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Classifier }
     * 
     * 
     */
    public List<Classifier> getClassifier() {
        if (classifier == null) {
            classifier = new ArrayList<Classifier>();
        }
        return this.classifier;
    }

    public boolean isSetClassifier() {
        return ((this.classifier!= null)&&(!this.classifier.isEmpty()));
    }

    public void unsetClassifier() {
        this.classifier = null;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<Classifier> theClassifier;
            theClassifier = (this.isSetClassifier()?this.getClassifier():null);
            strategy.appendField(locator, this, "classifier", buffer, theClassifier, this.isSetClassifier());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final ClassifierListType that = ((ClassifierListType) object);
        {
            List<Classifier> lhsClassifier;
            lhsClassifier = (this.isSetClassifier()?this.getClassifier():null);
            List<Classifier> rhsClassifier;
            rhsClassifier = (that.isSetClassifier()?that.getClassifier():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "classifier", lhsClassifier), LocatorUtils.property(thatLocator, "classifier", rhsClassifier), lhsClassifier, rhsClassifier, this.isSetClassifier(), that.isSetClassifier())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<Classifier> theClassifier;
            theClassifier = (this.isSetClassifier()?this.getClassifier():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "classifier", theClassifier), currentHashCode, theClassifier, this.isSetClassifier());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof ClassifierListType) {
            final ClassifierListType copy = ((ClassifierListType) draftCopy);
            {
                Boolean classifierShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetClassifier());
                if (classifierShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<Classifier> sourceClassifier;
                    sourceClassifier = (this.isSetClassifier()?this.getClassifier():null);
                    @SuppressWarnings("unchecked")
                    List<Classifier> copyClassifier = ((List<Classifier> ) strategy.copy(LocatorUtils.property(locator, "classifier", sourceClassifier), sourceClassifier, this.isSetClassifier()));
                    copy.unsetClassifier();
                    if (copyClassifier!= null) {
                        List<Classifier> uniqueClassifierl = copy.getClassifier();
                        uniqueClassifierl.addAll(copyClassifier);
                    }
                } else {
                    if (classifierShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetClassifier();
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new ClassifierListType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof ClassifierListType) {
            final ClassifierListType target = this;
            final ClassifierListType leftObject = ((ClassifierListType) left);
            final ClassifierListType rightObject = ((ClassifierListType) right);
            {
                Boolean classifierShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetClassifier(), rightObject.isSetClassifier());
                if (classifierShouldBeMergedAndSet == Boolean.TRUE) {
                    List<Classifier> lhsClassifier;
                    lhsClassifier = (leftObject.isSetClassifier()?leftObject.getClassifier():null);
                    List<Classifier> rhsClassifier;
                    rhsClassifier = (rightObject.isSetClassifier()?rightObject.getClassifier():null);
                    List<Classifier> mergedClassifier = ((List<Classifier> ) strategy.merge(LocatorUtils.property(leftLocator, "classifier", lhsClassifier), LocatorUtils.property(rightLocator, "classifier", rhsClassifier), lhsClassifier, rhsClassifier, leftObject.isSetClassifier(), rightObject.isSetClassifier()));
                    target.unsetClassifier();
                    if (mergedClassifier!= null) {
                        List<Classifier> uniqueClassifierl = target.getClassifier();
                        uniqueClassifierl.addAll(mergedClassifier);
                    }
                } else {
                    if (classifierShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetClassifier();
                    }
                }
            }
        }
    }

    public void setClassifier(List<Classifier> value) {
        this.classifier = null;
        if (value!= null) {
            List<Classifier> draftl = this.getClassifier();
            draftl.addAll(value);
        }
    }

    public ClassifierListType withClassifier(Classifier... values) {
        if (values!= null) {
            for (Classifier value: values) {
                getClassifier().add(value);
            }
        }
        return this;
    }

    public ClassifierListType withClassifier(Collection<Classifier> values) {
        if (values!= null) {
            getClassifier().addAll(values);
        }
        return this;
    }

    public ClassifierListType withClassifier(List<Classifier> value) {
        setClassifier(value);
        return this;
    }

    @Override
    public ClassifierListType withDefinition(String value) {
        setDefinition(value);
        return this;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element ref="{http://www.opengis.net/sensorml/2.0}Term"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "term"
    })
    public static class Classifier implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
    {

        @XmlElement(name = "Term", required = true)
        protected TermType term;

        /**
         * Gets the value of the term property.
         * 
         * @return
         *     possible object is
         *     {@link TermType }
         *     
         */
        public TermType getTerm() {
            return term;
        }

        /**
         * Sets the value of the term property.
         * 
         * @param value
         *     allowed object is
         *     {@link TermType }
         *     
         */
        public void setTerm(TermType value) {
            this.term = value;
        }

        public boolean isSetTerm() {
            return (this.term!= null);
        }

        public String toString() {
            final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
            final StringBuilder buffer = new StringBuilder();
            append(null, buffer, strategy);
            return buffer.toString();
        }

        public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            strategy.appendStart(locator, this, buffer);
            appendFields(locator, buffer, strategy);
            strategy.appendEnd(locator, this, buffer);
            return buffer;
        }

        public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
            {
                TermType theTerm;
                theTerm = this.getTerm();
                strategy.appendField(locator, this, "term", buffer, theTerm, this.isSetTerm());
            }
            return buffer;
        }

        public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
            if ((object == null)||(this.getClass()!= object.getClass())) {
                return false;
            }
            if (this == object) {
                return true;
            }
            final Classifier that = ((Classifier) object);
            {
                TermType lhsTerm;
                lhsTerm = this.getTerm();
                TermType rhsTerm;
                rhsTerm = that.getTerm();
                if (!strategy.equals(LocatorUtils.property(thisLocator, "term", lhsTerm), LocatorUtils.property(thatLocator, "term", rhsTerm), lhsTerm, rhsTerm, this.isSetTerm(), that.isSetTerm())) {
                    return false;
                }
            }
            return true;
        }

        public boolean equals(Object object) {
            final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
            return equals(null, null, object, strategy);
        }

        public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
            int currentHashCode = 1;
            {
                TermType theTerm;
                theTerm = this.getTerm();
                currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "term", theTerm), currentHashCode, theTerm, this.isSetTerm());
            }
            return currentHashCode;
        }

        public int hashCode() {
            final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
            return this.hashCode(null, strategy);
        }

        public Object clone() {
            return copyTo(createNewInstance());
        }

        public Object copyTo(Object target) {
            final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
            return copyTo(null, target, strategy);
        }

        public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
            final Object draftCopy = ((target == null)?createNewInstance():target);
            if (draftCopy instanceof Classifier) {
                final Classifier copy = ((Classifier) draftCopy);
                {
                    Boolean termShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetTerm());
                    if (termShouldBeCopiedAndSet == Boolean.TRUE) {
                        TermType sourceTerm;
                        sourceTerm = this.getTerm();
                        TermType copyTerm = ((TermType) strategy.copy(LocatorUtils.property(locator, "term", sourceTerm), sourceTerm, this.isSetTerm()));
                        copy.setTerm(copyTerm);
                    } else {
                        if (termShouldBeCopiedAndSet == Boolean.FALSE) {
                            copy.term = null;
                        }
                    }
                }
            }
            return draftCopy;
        }

        public Object createNewInstance() {
            return new Classifier();
        }

        public void mergeFrom(Object left, Object right) {
            final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
            mergeFrom(null, null, left, right, strategy);
        }

        public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
            if (right instanceof Classifier) {
                final Classifier target = this;
                final Classifier leftObject = ((Classifier) left);
                final Classifier rightObject = ((Classifier) right);
                {
                    Boolean termShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetTerm(), rightObject.isSetTerm());
                    if (termShouldBeMergedAndSet == Boolean.TRUE) {
                        TermType lhsTerm;
                        lhsTerm = leftObject.getTerm();
                        TermType rhsTerm;
                        rhsTerm = rightObject.getTerm();
                        TermType mergedTerm = ((TermType) strategy.merge(LocatorUtils.property(leftLocator, "term", lhsTerm), LocatorUtils.property(rightLocator, "term", rhsTerm), lhsTerm, rhsTerm, leftObject.isSetTerm(), rightObject.isSetTerm()));
                        target.setTerm(mergedTerm);
                    } else {
                        if (termShouldBeMergedAndSet == Boolean.FALSE) {
                            target.term = null;
                        }
                    }
                }
            }
        }

        public Classifier withTerm(TermType value) {
            setTerm(value);
            return this;
        }

    }

}
