//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.14 at 04:45:11 PM CEST 
//


package eu.essi_lab.jaxb.sos._2_0.wml;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;

import eu.essi_lab.jaxb.sos._2_0.gml._3_2_1.ReferenceType;
import eu.essi_lab.jaxb.sos._2_0.swe._2.QuantityPropertyType;
import eu.essi_lab.jaxb.sos._2_0.swe._2.UnitReference;


/**
 * <p>Java class for TVPMeasurementMetadataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TVPMeasurementMetadataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/waterml/2.0}TVPMetadataType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="uom" type="{http://www.opengis.net/swe/2.0}UnitReference" minOccurs="0"/&gt;
 *         &lt;element name="interpolationType" type="{http://www.opengis.net/gml/3.2}ReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="censoredReason" type="{http://www.opengis.net/gml/3.2}ReferenceType" minOccurs="0"/&gt;
 *         &lt;element name="accuracy" type="{http://www.opengis.net/swe/2.0}QuantityPropertyType" minOccurs="0"/&gt;
 *         &lt;element name="aggregationDuration" type="{http://www.w3.org/2001/XMLSchema}duration" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVPMeasurementMetadataType", propOrder = {
    "uom",
    "interpolationType",
    "censoredReason",
    "accuracy",
    "aggregationDuration"
})
public class TVPMeasurementMetadataType
    extends TVPMetadataType
{

    protected UnitReference uom;
    protected ReferenceType interpolationType;
    protected ReferenceType censoredReason;
    protected QuantityPropertyType accuracy;
    protected Duration aggregationDuration;

    /**
     * Gets the value of the uom property.
     * 
     * @return
     *     possible object is
     *     {@link UnitReference }
     *     
     */
    public UnitReference getUom() {
        return uom;
    }

    /**
     * Sets the value of the uom property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitReference }
     *     
     */
    public void setUom(UnitReference value) {
        this.uom = value;
    }

    /**
     * Gets the value of the interpolationType property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getInterpolationType() {
        return interpolationType;
    }

    /**
     * Sets the value of the interpolationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setInterpolationType(ReferenceType value) {
        this.interpolationType = value;
    }

    /**
     * Gets the value of the censoredReason property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceType }
     *     
     */
    public ReferenceType getCensoredReason() {
        return censoredReason;
    }

    /**
     * Sets the value of the censoredReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceType }
     *     
     */
    public void setCensoredReason(ReferenceType value) {
        this.censoredReason = value;
    }

    /**
     * Gets the value of the accuracy property.
     * 
     * @return
     *     possible object is
     *     {@link QuantityPropertyType }
     *     
     */
    public QuantityPropertyType getAccuracy() {
        return accuracy;
    }

    /**
     * Sets the value of the accuracy property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuantityPropertyType }
     *     
     */
    public void setAccuracy(QuantityPropertyType value) {
        this.accuracy = value;
    }

    /**
     * Gets the value of the aggregationDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getAggregationDuration() {
        return aggregationDuration;
    }

    /**
     * Sets the value of the aggregationDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setAggregationDuration(Duration value) {
        this.aggregationDuration = value;
    }

}
