apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "frost.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  selector:
    app: postgres
    {{- include "frost.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    protocol: TCP
    name: postgres
  type: {{ .Values.postgres.service.type }}

