//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.02.26 at 04:37:09 PM AST 
//


package net.opengis.gml.v_3_1_1;

/*-
 * #%L
 * Discovery and Access Broker (DAB)
 * %%
 * Copyright (C) 2021 - 2026 National Research Council of Italy (CNR)/Institute of Atmospheric Pollution Research (IIA)/ESSI-Lab
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 * #L%
 */

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * The definition of a group of parameters used by an operation method. This complexType is expected to be used or extended for all applicable operation methods, without defining operation-method-specialized element names.  
 * 
 * <p>Java class for OperationParameterGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationParameterGroupType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.opengis.net/gml}OperationParameterGroupBaseType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}groupID" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}remarks" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}maximumOccurs" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.opengis.net/gml}includesParameter" maxOccurs="unbounded" minOccurs="2"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationParameterGroupType", propOrder = {
    "groupID",
    "remarks",
    "maximumOccurs",
    "includesParameter"
})
public class OperationParameterGroupType
    extends OperationParameterGroupBaseType
    implements Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    protected List<IdentifierType> groupID;
    protected StringOrRefType remarks;
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger maximumOccurs;
    @XmlElement(required = true)
    protected List<AbstractGeneralOperationParameterRefType> includesParameter;

    /**
     * Set of alternative identifications of this operation parameter group. The first groupID, if any, is normally the primary identification code, and any others are aliases. Gets the value of the groupID property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the groupID property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGroupID().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IdentifierType }
     * 
     * 
     */
    public List<IdentifierType> getGroupID() {
        if (groupID == null) {
            groupID = new ArrayList<IdentifierType>();
        }
        return this.groupID;
    }

    public boolean isSetGroupID() {
        return ((this.groupID!= null)&&(!this.groupID.isEmpty()));
    }

    public void unsetGroupID() {
        this.groupID = null;
    }

    /**
     * Comments on or information about this operation parameter group, including source information. 
     * 
     * @return
     *     possible object is
     *     {@link StringOrRefType }
     *     
     */
    public StringOrRefType getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringOrRefType }
     *     
     */
    public void setRemarks(StringOrRefType value) {
        this.remarks = value;
    }

    public boolean isSetRemarks() {
        return (this.remarks!= null);
    }

    /**
     * Gets the value of the maximumOccurs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaximumOccurs() {
        return maximumOccurs;
    }

    /**
     * Sets the value of the maximumOccurs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaximumOccurs(BigInteger value) {
        this.maximumOccurs = value;
    }

    public boolean isSetMaximumOccurs() {
        return (this.maximumOccurs!= null);
    }

    /**
     * Unordered list of associations to the set of operation parameters that are members of this group. Gets the value of the includesParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includesParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludesParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AbstractGeneralOperationParameterRefType }
     * 
     * 
     */
    public List<AbstractGeneralOperationParameterRefType> getIncludesParameter() {
        if (includesParameter == null) {
            includesParameter = new ArrayList<AbstractGeneralOperationParameterRefType>();
        }
        return this.includesParameter;
    }

    public boolean isSetIncludesParameter() {
        return ((this.includesParameter!= null)&&(!this.includesParameter.isEmpty()));
    }

    public void unsetIncludesParameter() {
        this.includesParameter = null;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        super.appendFields(locator, buffer, strategy);
        {
            List<IdentifierType> theGroupID;
            theGroupID = (this.isSetGroupID()?this.getGroupID():null);
            strategy.appendField(locator, this, "groupID", buffer, theGroupID, this.isSetGroupID());
        }
        {
            StringOrRefType theRemarks;
            theRemarks = this.getRemarks();
            strategy.appendField(locator, this, "remarks", buffer, theRemarks, this.isSetRemarks());
        }
        {
            BigInteger theMaximumOccurs;
            theMaximumOccurs = this.getMaximumOccurs();
            strategy.appendField(locator, this, "maximumOccurs", buffer, theMaximumOccurs, this.isSetMaximumOccurs());
        }
        {
            List<AbstractGeneralOperationParameterRefType> theIncludesParameter;
            theIncludesParameter = (this.isSetIncludesParameter()?this.getIncludesParameter():null);
            strategy.appendField(locator, this, "includesParameter", buffer, theIncludesParameter, this.isSetIncludesParameter());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        if (!super.equals(thisLocator, thatLocator, object, strategy)) {
            return false;
        }
        final OperationParameterGroupType that = ((OperationParameterGroupType) object);
        {
            List<IdentifierType> lhsGroupID;
            lhsGroupID = (this.isSetGroupID()?this.getGroupID():null);
            List<IdentifierType> rhsGroupID;
            rhsGroupID = (that.isSetGroupID()?that.getGroupID():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "groupID", lhsGroupID), LocatorUtils.property(thatLocator, "groupID", rhsGroupID), lhsGroupID, rhsGroupID, this.isSetGroupID(), that.isSetGroupID())) {
                return false;
            }
        }
        {
            StringOrRefType lhsRemarks;
            lhsRemarks = this.getRemarks();
            StringOrRefType rhsRemarks;
            rhsRemarks = that.getRemarks();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "remarks", lhsRemarks), LocatorUtils.property(thatLocator, "remarks", rhsRemarks), lhsRemarks, rhsRemarks, this.isSetRemarks(), that.isSetRemarks())) {
                return false;
            }
        }
        {
            BigInteger lhsMaximumOccurs;
            lhsMaximumOccurs = this.getMaximumOccurs();
            BigInteger rhsMaximumOccurs;
            rhsMaximumOccurs = that.getMaximumOccurs();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "maximumOccurs", lhsMaximumOccurs), LocatorUtils.property(thatLocator, "maximumOccurs", rhsMaximumOccurs), lhsMaximumOccurs, rhsMaximumOccurs, this.isSetMaximumOccurs(), that.isSetMaximumOccurs())) {
                return false;
            }
        }
        {
            List<AbstractGeneralOperationParameterRefType> lhsIncludesParameter;
            lhsIncludesParameter = (this.isSetIncludesParameter()?this.getIncludesParameter():null);
            List<AbstractGeneralOperationParameterRefType> rhsIncludesParameter;
            rhsIncludesParameter = (that.isSetIncludesParameter()?that.getIncludesParameter():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "includesParameter", lhsIncludesParameter), LocatorUtils.property(thatLocator, "includesParameter", rhsIncludesParameter), lhsIncludesParameter, rhsIncludesParameter, this.isSetIncludesParameter(), that.isSetIncludesParameter())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = super.hashCode(locator, strategy);
        {
            List<IdentifierType> theGroupID;
            theGroupID = (this.isSetGroupID()?this.getGroupID():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "groupID", theGroupID), currentHashCode, theGroupID, this.isSetGroupID());
        }
        {
            StringOrRefType theRemarks;
            theRemarks = this.getRemarks();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "remarks", theRemarks), currentHashCode, theRemarks, this.isSetRemarks());
        }
        {
            BigInteger theMaximumOccurs;
            theMaximumOccurs = this.getMaximumOccurs();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "maximumOccurs", theMaximumOccurs), currentHashCode, theMaximumOccurs, this.isSetMaximumOccurs());
        }
        {
            List<AbstractGeneralOperationParameterRefType> theIncludesParameter;
            theIncludesParameter = (this.isSetIncludesParameter()?this.getIncludesParameter():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "includesParameter", theIncludesParameter), currentHashCode, theIncludesParameter, this.isSetIncludesParameter());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        super.copyTo(locator, draftCopy, strategy);
        if (draftCopy instanceof OperationParameterGroupType) {
            final OperationParameterGroupType copy = ((OperationParameterGroupType) draftCopy);
            {
                Boolean groupIDShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetGroupID());
                if (groupIDShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<IdentifierType> sourceGroupID;
                    sourceGroupID = (this.isSetGroupID()?this.getGroupID():null);
                    @SuppressWarnings("unchecked")
                    List<IdentifierType> copyGroupID = ((List<IdentifierType> ) strategy.copy(LocatorUtils.property(locator, "groupID", sourceGroupID), sourceGroupID, this.isSetGroupID()));
                    copy.unsetGroupID();
                    if (copyGroupID!= null) {
                        List<IdentifierType> uniqueGroupIDl = copy.getGroupID();
                        uniqueGroupIDl.addAll(copyGroupID);
                    }
                } else {
                    if (groupIDShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetGroupID();
                    }
                }
            }
            {
                Boolean remarksShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetRemarks());
                if (remarksShouldBeCopiedAndSet == Boolean.TRUE) {
                    StringOrRefType sourceRemarks;
                    sourceRemarks = this.getRemarks();
                    StringOrRefType copyRemarks = ((StringOrRefType) strategy.copy(LocatorUtils.property(locator, "remarks", sourceRemarks), sourceRemarks, this.isSetRemarks()));
                    copy.setRemarks(copyRemarks);
                } else {
                    if (remarksShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.remarks = null;
                    }
                }
            }
            {
                Boolean maximumOccursShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetMaximumOccurs());
                if (maximumOccursShouldBeCopiedAndSet == Boolean.TRUE) {
                    BigInteger sourceMaximumOccurs;
                    sourceMaximumOccurs = this.getMaximumOccurs();
                    BigInteger copyMaximumOccurs = ((BigInteger) strategy.copy(LocatorUtils.property(locator, "maximumOccurs", sourceMaximumOccurs), sourceMaximumOccurs, this.isSetMaximumOccurs()));
                    copy.setMaximumOccurs(copyMaximumOccurs);
                } else {
                    if (maximumOccursShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.maximumOccurs = null;
                    }
                }
            }
            {
                Boolean includesParameterShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetIncludesParameter());
                if (includesParameterShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<AbstractGeneralOperationParameterRefType> sourceIncludesParameter;
                    sourceIncludesParameter = (this.isSetIncludesParameter()?this.getIncludesParameter():null);
                    @SuppressWarnings("unchecked")
                    List<AbstractGeneralOperationParameterRefType> copyIncludesParameter = ((List<AbstractGeneralOperationParameterRefType> ) strategy.copy(LocatorUtils.property(locator, "includesParameter", sourceIncludesParameter), sourceIncludesParameter, this.isSetIncludesParameter()));
                    copy.unsetIncludesParameter();
                    if (copyIncludesParameter!= null) {
                        List<AbstractGeneralOperationParameterRefType> uniqueIncludesParameterl = copy.getIncludesParameter();
                        uniqueIncludesParameterl.addAll(copyIncludesParameter);
                    }
                } else {
                    if (includesParameterShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetIncludesParameter();
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new OperationParameterGroupType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        super.mergeFrom(leftLocator, rightLocator, left, right, strategy);
        if (right instanceof OperationParameterGroupType) {
            final OperationParameterGroupType target = this;
            final OperationParameterGroupType leftObject = ((OperationParameterGroupType) left);
            final OperationParameterGroupType rightObject = ((OperationParameterGroupType) right);
            {
                Boolean groupIDShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetGroupID(), rightObject.isSetGroupID());
                if (groupIDShouldBeMergedAndSet == Boolean.TRUE) {
                    List<IdentifierType> lhsGroupID;
                    lhsGroupID = (leftObject.isSetGroupID()?leftObject.getGroupID():null);
                    List<IdentifierType> rhsGroupID;
                    rhsGroupID = (rightObject.isSetGroupID()?rightObject.getGroupID():null);
                    List<IdentifierType> mergedGroupID = ((List<IdentifierType> ) strategy.merge(LocatorUtils.property(leftLocator, "groupID", lhsGroupID), LocatorUtils.property(rightLocator, "groupID", rhsGroupID), lhsGroupID, rhsGroupID, leftObject.isSetGroupID(), rightObject.isSetGroupID()));
                    target.unsetGroupID();
                    if (mergedGroupID!= null) {
                        List<IdentifierType> uniqueGroupIDl = target.getGroupID();
                        uniqueGroupIDl.addAll(mergedGroupID);
                    }
                } else {
                    if (groupIDShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetGroupID();
                    }
                }
            }
            {
                Boolean remarksShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetRemarks(), rightObject.isSetRemarks());
                if (remarksShouldBeMergedAndSet == Boolean.TRUE) {
                    StringOrRefType lhsRemarks;
                    lhsRemarks = leftObject.getRemarks();
                    StringOrRefType rhsRemarks;
                    rhsRemarks = rightObject.getRemarks();
                    StringOrRefType mergedRemarks = ((StringOrRefType) strategy.merge(LocatorUtils.property(leftLocator, "remarks", lhsRemarks), LocatorUtils.property(rightLocator, "remarks", rhsRemarks), lhsRemarks, rhsRemarks, leftObject.isSetRemarks(), rightObject.isSetRemarks()));
                    target.setRemarks(mergedRemarks);
                } else {
                    if (remarksShouldBeMergedAndSet == Boolean.FALSE) {
                        target.remarks = null;
                    }
                }
            }
            {
                Boolean maximumOccursShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetMaximumOccurs(), rightObject.isSetMaximumOccurs());
                if (maximumOccursShouldBeMergedAndSet == Boolean.TRUE) {
                    BigInteger lhsMaximumOccurs;
                    lhsMaximumOccurs = leftObject.getMaximumOccurs();
                    BigInteger rhsMaximumOccurs;
                    rhsMaximumOccurs = rightObject.getMaximumOccurs();
                    BigInteger mergedMaximumOccurs = ((BigInteger) strategy.merge(LocatorUtils.property(leftLocator, "maximumOccurs", lhsMaximumOccurs), LocatorUtils.property(rightLocator, "maximumOccurs", rhsMaximumOccurs), lhsMaximumOccurs, rhsMaximumOccurs, leftObject.isSetMaximumOccurs(), rightObject.isSetMaximumOccurs()));
                    target.setMaximumOccurs(mergedMaximumOccurs);
                } else {
                    if (maximumOccursShouldBeMergedAndSet == Boolean.FALSE) {
                        target.maximumOccurs = null;
                    }
                }
            }
            {
                Boolean includesParameterShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetIncludesParameter(), rightObject.isSetIncludesParameter());
                if (includesParameterShouldBeMergedAndSet == Boolean.TRUE) {
                    List<AbstractGeneralOperationParameterRefType> lhsIncludesParameter;
                    lhsIncludesParameter = (leftObject.isSetIncludesParameter()?leftObject.getIncludesParameter():null);
                    List<AbstractGeneralOperationParameterRefType> rhsIncludesParameter;
                    rhsIncludesParameter = (rightObject.isSetIncludesParameter()?rightObject.getIncludesParameter():null);
                    List<AbstractGeneralOperationParameterRefType> mergedIncludesParameter = ((List<AbstractGeneralOperationParameterRefType> ) strategy.merge(LocatorUtils.property(leftLocator, "includesParameter", lhsIncludesParameter), LocatorUtils.property(rightLocator, "includesParameter", rhsIncludesParameter), lhsIncludesParameter, rhsIncludesParameter, leftObject.isSetIncludesParameter(), rightObject.isSetIncludesParameter()));
                    target.unsetIncludesParameter();
                    if (mergedIncludesParameter!= null) {
                        List<AbstractGeneralOperationParameterRefType> uniqueIncludesParameterl = target.getIncludesParameter();
                        uniqueIncludesParameterl.addAll(mergedIncludesParameter);
                    }
                } else {
                    if (includesParameterShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetIncludesParameter();
                    }
                }
            }
        }
    }

    public void setGroupID(List<IdentifierType> value) {
        this.groupID = null;
        if (value!= null) {
            List<IdentifierType> draftl = this.getGroupID();
            draftl.addAll(value);
        }
    }

    public void setIncludesParameter(List<AbstractGeneralOperationParameterRefType> value) {
        this.includesParameter = null;
        if (value!= null) {
            List<AbstractGeneralOperationParameterRefType> draftl = this.getIncludesParameter();
            draftl.addAll(value);
        }
    }

    public OperationParameterGroupType withGroupID(IdentifierType... values) {
        if (values!= null) {
            for (IdentifierType value: values) {
                getGroupID().add(value);
            }
        }
        return this;
    }

    public OperationParameterGroupType withGroupID(Collection<IdentifierType> values) {
        if (values!= null) {
            getGroupID().addAll(values);
        }
        return this;
    }

    public OperationParameterGroupType withRemarks(StringOrRefType value) {
        setRemarks(value);
        return this;
    }

    public OperationParameterGroupType withMaximumOccurs(BigInteger value) {
        setMaximumOccurs(value);
        return this;
    }

    public OperationParameterGroupType withIncludesParameter(AbstractGeneralOperationParameterRefType... values) {
        if (values!= null) {
            for (AbstractGeneralOperationParameterRefType value: values) {
                getIncludesParameter().add(value);
            }
        }
        return this;
    }

    public OperationParameterGroupType withIncludesParameter(Collection<AbstractGeneralOperationParameterRefType> values) {
        if (values!= null) {
            getIncludesParameter().addAll(values);
        }
        return this;
    }

    public OperationParameterGroupType withGroupID(List<IdentifierType> value) {
        setGroupID(value);
        return this;
    }

    public OperationParameterGroupType withIncludesParameter(List<AbstractGeneralOperationParameterRefType> value) {
        setIncludesParameter(value);
        return this;
    }

    @Override
    public OperationParameterGroupType withMinimumOccurs(BigInteger value) {
        setMinimumOccurs(value);
        return this;
    }

    @Override
    public OperationParameterGroupType withMetaDataProperty(MetaDataPropertyType... values) {
        if (values!= null) {
            for (MetaDataPropertyType value: values) {
                getMetaDataProperty().add(value);
            }
        }
        return this;
    }

    @Override
    public OperationParameterGroupType withMetaDataProperty(Collection<MetaDataPropertyType> values) {
        if (values!= null) {
            getMetaDataProperty().addAll(values);
        }
        return this;
    }

    @Override
    public OperationParameterGroupType withDescription(StringOrRefType value) {
        setDescription(value);
        return this;
    }

    @Override
    public OperationParameterGroupType withName(JAXBElement<CodeType> ... values) {
        if (values!= null) {
            for (JAXBElement<CodeType> value: values) {
                getName().add(value);
            }
        }
        return this;
    }

    @Override
    public OperationParameterGroupType withName(Collection<JAXBElement<CodeType>> values) {
        if (values!= null) {
            getName().addAll(values);
        }
        return this;
    }

    @Override
    public OperationParameterGroupType withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public OperationParameterGroupType withMetaDataProperty(List<MetaDataPropertyType> value) {
        setMetaDataProperty(value);
        return this;
    }

    @Override
    public OperationParameterGroupType withName(List<JAXBElement<CodeType>> value) {
        setName(value);
        return this;
    }

}
